### ISSUE TITLE
Doesn't work with Safari WebGL2 Experimental Beta

### ISSUE THREAD

**Issue by OKNoah** [magcius/noclip.website#10]
WebGLReport says "This browser supports WebGL 2"

```
Platform: | MacIntel
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
webgl2
WebGL 2.0 (4.1 INTEL-12.4.7)
WebGL GLSL ES 1.0 (4.10)
WebKit
WebKit WebGL
Intel Inc.
Intel(R) Iris(TM) Plus Graphics 655
Not available
No
No

Supported Extensions:
  WEBKIT_EXT_texture_filter_anisotropic
  WEBGL_compressed_texture_s3tc
  WEBGL_lose_context
  WEBGL_debug_renderer_info
 
WebGL 2 Functions Implementation Status:
  88 of 88 new functions implemented.
```

EDIT: This is with WebGL 2 supported enabled through the developer menu.

**Comment by magcius** [comment]
What error do you see on noclip.website?

**Comment by OKNoah** [comment]
@magcius The one that says to do a test and post here :)

**Comment by magcius** [comment]
Can you post the exact contents of the message? There are several error messages that tell you to do that. A screenshot of the WebGLReport page would be appreciated as well.

**Comment by OKNoah** [comment]
@magcius 

```
This browser has a non-functioning version of WebGL 2 that I have not seen before.

If WebGL Report says your browser supports WebGL 2, please open a GitHub issue with as much as information as possible.

Thanks, Jasper.
```

**Comment by magcius** [comment]
That means that there is no antialiasing support -- I'm guessing Safari has an incomplete implementation of WebGL2 or no AA support in general.

**Comment by simonrolfe** [comment]
Same issue with iOS Safari, which, according to WebGLReport supports “88 of 88 new functions”. Screenshot of report attached, I hope that helps! 
![e1bb71e3-4a42-43eb-98d1-16c6713b780d](https://user-images.githubusercontent.com/5150058/53375910-88670600-3954-11e9-8a7d-3cc9dbc7fa3b.png)

**Comment by magcius** [comment]
"Antialiasing: Not supported"

This is the issue. When I get some spare time, I'll investigate rewriting the site without antialiasing. But I do not have an iDevice to test on so it'll be blind.

**Comment by TimvanScherpenzeel** [comment]
WebGL2 on Safari (iOS and Mac) experimentally supports WebGL2 but does not support the `# version 300es` shader which is required for creating valid shaders in WebGL2. This means that the current implementation is not yet complete. 

![screen shot 2019-02-26 at 14 47 41](https://user-images.githubusercontent.com/11870513/53417474-f99acd80-39d5-11e9-85e4-a2230e483d2e.png)

You can test it yourself on [WebGL2Samples](http://webglsamples.org/WebGL2Samples/).

**Comment by magcius** [comment]
Indeed, I don't think Safari's WebGL2 Experimental Beta is complete enough to support. The upstream WebKit bug is at https://bugs.webkit.org/show_bug.cgi?id=126404

Note that there is work on a new web standard, [WebGPU](https://github.com/gpuweb/gpuweb/). I will support WebGPU once it starts becoming available in browsers.

**Comment by OKNoah** [comment]
@magcius Thanks for considering support sans-antialiasing. Apple devices have Retina display in the range of 300-458ppi anyhow. Some say this reduces the need for antialiasing, although it's debatable. Maybe Apple agrees, or is planning some sort of browser-wide (maybe hardware based) antialiasing solution? Anyway, thanks for intending to support the greatest browser ever, Safari.

**Comment by magcius** [comment]
As @TimvanScherpenzeel has pointed out, even if we remove the requirement for antialiasing support, the shader compiler is not even remotely near finished.

**Comment by OKNoah** [comment]
@magcius Noted. BTW, Safari Technology Preview doesn't show any on-screen errors. Sadly, I don't think it works either:

`WebGL: INVALID_FRAMEBUFFER_OPERATION: drawArrays: attachment type is not correct for attachment`

The version I'm using can be found here: 
https://secure-appldnld.apple.com/STP/041-40625-20190220-BF218A9D-C022-47E2-B5B8-8B963AAF9D87/SafariTechnologyPreview.dmg

The page to download the latest is here: https://developer.apple.com/safari/download

I hope this is helpful!

**Comment by magcius** [comment]
I do not have a Mac myself, so I cannot test the Safari Technology Preview.

**Comment by Something6666** [comment]
I've had the same problem, I hope Jasper fixes this soon

**Comment by Goatfatman** [comment]
I got an error saying that WebGL is suppported but is not turned on or unavaible what do I do?

**Comment by magcius** [comment]
What browser are you using? Can you post a screenshot of https://webglreport.com/?v=2 ?

**Comment by Goatfatman** [comment]
I'm using Chrome. [cid:e774e549-ddec-4257-815b-38bed4d61f7a]
________________________________

**Comment by magcius** [comment]
Please file a new bug through https://github.com/magcius/noclip.website/issues/new?template=tech_support.md -- this issue is tracking for Safarai support. Make sure to attach the screenshot there, as the one attached to your email did not appear to make it through.

**Comment by magcius** [comment]
https://twitter.com/grorgwork/status/1289679221313290240

> Since there is discussion across multiple twitter threads (thwreads?) I'll say it here. Apple doesn't comment on future releases of Safari/iOS/macOS/etc, but I am planning to turn WebGL2 on by default in Safari Technology Preview in about 4 weeks.

**Comment by magcius** [comment]
I do not have a Mac to test on, but according to this tweet, the new Safari Technical Preview should have possibly-working WebGL 2 support, based on the new ANGLE implementation. Can anyone test noclip on it?

https://twitter.com/grorgwork/status/1288929511493386240

**Comment by CryZe** [comment]
At least on iOS it seems to mostly works, but the shaders are super broken.

![image](https://user-images.githubusercontent.com/1451630/89127974-5dda8e80-d4f2-11ea-8723-38011d694e67.png)

**Comment by magcius** [comment]
WebGL 2 now works in the latest Safari Technical Preview, and several people have confirmed that noclip.website runs, albeit somewhat poorly. I am closing this now.
