### ISSUE TITLE
OpenGL2 is supported on MobileSafari with the OpenGL2 experimental option enabled

### ISSUE THREAD

**Issue by BenjaminUrquhart** [magcius/noclip.website#100]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![8CB0FA2D-9711-44BE-BE89-F097D5FCED05](https://user-images.githubusercontent.com/24701883/63229749-d6591a00-c1d1-11e9-8108-0445d5e07560.png)
![2D3E8875-0204-4410-807D-E02B82B7D2AA](https://user-images.githubusercontent.com/24701883/63229750-d6591a00-c1d1-11e9-8692-c3466e576c82.png)

**Comment by magcius** [comment]
WebGL 2.0 preview is effectively pointless. See #10.
