### ISSUE TITLE
I am using OS X El Capitan I am Using Intel HD graphics and Im using google chrome  Version 76.0.3809.132version I went to the webgl site I don't want to screenshot (privacy reasons) but It says it supports Google Chrome can you please help

### ISSUE THREAD

**Issue by Idkwhatscool** [magcius/noclip.website#105]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

**Comment by magcius** [comment]
What error message are you seeing on noclip?
