### ISSUE TITLE
hardware acceleration not detected even when enabled (CentOS/Chrome/NVIDIA GP107)

### ISSUE THREAD

**Issue by bouc** [magcius/noclip.website#107]
Error:
![image](https://user-images.githubusercontent.com/3698516/64496030-c8e1fd80-d26e-11e9-927b-d768973ce69f.png)

![image](https://user-images.githubusercontent.com/3698516/64496041-e7e08f80-d26e-11e9-9206-872a3ced679e.png)

Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
_CentOS Linux release 7.6.1810 (Core)_

What **GPU and Driver Version** are you using?
_NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
NVIDIA dlloader X Driver  430.26_

What **Browser and Version** are you using?
_Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)_

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/3698516/64496016-9932f580-d26e-11e9-8a82-eb1a92b6ad66.png)

**Comment by magcius** [comment]
> Unmasked Renderer: Google SwiftShader

I don't know why, but for some reason the hardware acceleration isn't working. `chrome://gpu` might have more details.

**Comment by bouc** [comment]
Does this help?
![image](https://user-images.githubusercontent.com/3698516/64496164-fbd8c100-d26f-11e9-9783-329ff9cd6512.png)

**Comment by magcius** [comment]
There's a giant log at the end which might give you details into why Chrome disabled to force HW acceleration off.

**Comment by bouc** [comment]
Guess the OS is not supported
"Accelerated video decode is unavailable on Linux: 137247"
https://bugs.chromium.org/p/chromium/issues/detail?id=137247

**Comment by magcius** [comment]
Video decode should be unrelated to GPU acceleration

**Comment by bouc** [comment]
Either way, it seems the issue is not on your end. Thanks for prompt replies.
