### ISSUE TITLE
Can't move the camera in Wind Waker "Fire Mountain"

### ISSUE THREAD

**Issue by quat1024** [magcius/noclip.website#11]
Hi, love the site! Here's a little bug I found when trying to open one of the maps.

1. set the camera to "WASD" mode
2. open The Legend of Zelda: The Wind Waker -> Unused Test Maps -> Fire Mountain
3. Try to move the camera with the mouse or wasd
4. You can't!
5. Switch the camera to Orbit and back while the map is open.
6. And now you are free to move the camera around the map, ~~and be underwhelmed by it.~~

I'm using Chrome and on build 450e4738 of the application.

This is printed to the console upon selecting the map.

![image](https://user-images.githubusercontent.com/2068021/53376948-3b703900-392e-11e9-93aa-b4f42fbcb8e7.png)

**Comment by magcius** [comment]
Yeah, this is a known issue I forgot to file. The map tries to access a set of palette colors that's not in the file data. Once I get some spare time I'll sit down and solve this. Thanks for the report!
