### ISSUE TITLE
noclip error

### ISSUE THREAD

**Issue by Ashton636** [magcius/noclip.website#122]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

**Comment by Ashton636** [comment]
Windows 7 Home Premium 6.1.7601
Google Chrome latest version

**Comment by magcius** [comment]
Please answer the questions.
