### ISSUE TITLE
im using windows 10 latest version. intel hd graphics 3000, also have nvs 4200m , but it disappeared after downloading optimus display drivers. chrome latest version

### ISSUE THREAD

**Issue by xxATOMxx** [magcius/noclip.website#126]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

**Comment by magcius** [comment]
Please take a screenshot of http://webglreport.com/?v=2 and paste it here.
