### ISSUE TITLE
noclip.website

### ISSUE THREAD

**Issue by MULTICOMP-LED-Blue-T** [magcius/noclip.website#127]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

1-) What **OS and Version** are you using?
- Windows 7 64-bit.

2-) What **GPU and Driver Version** are you using?
- AMD 760g. Ver 8.710.0.0

3-)What **Browser and Version** are you using?
- Opera version 63.0.3368.71

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/33363349/65381713-6c023080-dccd-11e9-8db0-71e2507e23ba.png)

**Comment by MULTICOMP-LED-Blue-T** [comment]
> Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:
> 
> 1-) What **OS and Version** are you using?
> 
> * Windows 7 64-bit.
> 
> 2-) What **GPU and Driver Version** are you using?
> 
> * AMD 760g. Ver 8.710.0.0
> 
> 3-)What **Browser and Version** are you using?
> 
> * Opera version 63.0.3368.71
> 
> Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
> ![image](https://user-images.githubusercontent.com/33363349/65381713-6c023080-dccd-11e9-8db0-71e2507e23ba.png)

**Comment by magcius** [comment]
> Unmasked Renderer: Google SwiftShader

This is not hardware accelerated. Try to enable hardware acceleration on your browser.
