### ISSUE TITLE
The page doesn't show up

### ISSUE THREAD

**Issue by antpergom** [magcius/noclip.website#131]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10 Pro (laptop)
What **GPU and Driver Version** are you using? NVIDIA GT 520MX (1GB)
What **Browser and Version** are you using? Google chrome Versión 77.0.3865.90 (Build oficial) (64 bits)
![webgl](https://user-images.githubusercontent.com/23011988/65618643-ed540e80-dfbe-11e9-8e9a-cc709ddcc7ad.PNG)

**Comment by magcius** [comment]
Do you have hardware acceleration enabled?
