### ISSUE TITLE
hello! I'm using Ubuntu 18.04.03

### ISSUE THREAD

**Issue by danfarrow** [magcius/noclip.website#133]
Hello, I just had a quick look at the site & saw the "your browser does not appear to to have WebGL 2" message

WebGL Report says otherwise so here I am :)

What **OS and Version** are you using? Ubuntu 18.04.3

What **GPU and Driver Version** are you using? GeForce GTX 1050, nvidia-driver-430

What **Browser and Version** are you using? Firefox 69.0.1

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/236580/65639920-0ec5f200-dfe1-11e9-8483-c3a10dee1990.png)

**Comment by magcius** [comment]
What error are you seeing?

**Comment by danfarrow** [comment]
I just looked again and I am no longer seeing an error - yay!
