### ISSUE TITLE
noclip.com issue 

### ISSUE THREAD

**Issue by greg-oops** [magcius/noclip.website#138]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? i dont know 
What **GPU and Driver Version** are you using? i dont know
What **Browser and Version** are you using? google chrome latest
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

**Comment by magcius** [comment]
Please answer the questions and post the requested screenshot.
