### ISSUE TITLE
WebGL said to be not working but my browser supports it

### ISSUE THREAD

**Issue by darkvertex** [magcius/noclip.website#139]
What **OS and Version** are you using?
CentOS Linux release 7.3.1611 (Core)

What **GPU and Driver Version** are you using?

- GeForce GT 730
- Driver Version: 430.26

What **Browser and Version** are you using?

Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

![webglreport](https://user-images.githubusercontent.com/941331/65919232-b78d9c00-e3a9-11e9-8b63-728e89c4622b.png)

**Comment by magcius** [comment]
> "Google SwiftShader"

This means you're using software rasterizing. Make sure that you turn on hardware acceleration in your browser's settings.
