### ISSUE TITLE
Explicit camera speed slider under Viewer Settings

### ISSUE THREAD

**Issue by spiral6** [magcius/noclip.website#16]
Pretty much exactly what's written on the title. The mouse wheel is very inconsistent and wonky to use.

**Comment by magcius** [comment]
Hi! Yeah, I agree this is something that should be there. It's complicated because of the "Orbit" camera controller, which arguably shouldn't exist at all. But it makes it hard for me to expose camera settings through the panel since what should the slider do on Orbit?

**Comment by magcius** [comment]
Added!

**Comment by spiral6** [comment]
Thanks!
