### ISSUE TITLE
Not working on my end; only getting menus over a black background (Firefox / Waterfox 56 unsupported)

### ISSUE THREAD

**Issue by Beed28** [magcius/noclip.website#17]
Doesn't seem to work for me; all I get is the menus over just a black background.

My browser (Waterfox 56.2.7.1) definitely supports WebGL 2.0, as going to http://webglreport.com/?v=2 gives a positive result, so I don't know what's going on here.

![image](https://user-images.githubusercontent.com/30600723/53417023-935d7d00-39cc-11e9-8330-85e7e1aaf8df.png)

**Comment by magcius** [comment]
Hi there! First up, it doesn't look like you've loaded any maps. Could you try loading, say, Coconut Mall from Mario Kart Wii? When that fails to load, could you open the Dev Tools console with F12, do you see any error messages?

**Comment by Nullpo** [comment]
Hi! I've the same problem.
The console says

`Uncaught ReferenceError: AbortController is not defined
    at e.loadSceneDesc (crc32.js:109)
    at t._loadSceneDesc (crc32.js:109)
    at t._onSceneDescSelected (crc32.js:109)
    at n.selectSceneDesc (index.js:1788)
    at n.sceneDescList.onselectionchange (index.js:1788)
    at n.selectItem (index.js:1788)
    at n.itemFocused (index.js:1788)
    at HTMLDivElement.r.onfocus (index.js:1788)
    at HTMLDivElement.r.onmousedown (index.js:1788)`

There is no problems in the network tab.
http://webglreport.com/?v=2 says " This browser supports WebGL 2"

Chrome Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by magcius** [comment]
`AbortController is not defined` ugh, it sounds like your browser doesn't have support for https://caniuse.com/#feat=abortcontroller . For now, could you try to use a different browser? When I get some time I will investigate an alternate solution.

**Comment by Beed28** [comment]
Tried Chrome and it works on there.

**Comment by magcius** [comment]
I think I'm going to have to close this as WONTFIX. Supporting older browsers would be too much work for me.

**Comment by grahamperrin** [comment]
Cross reference: [WEBGL 2 Support or how to enable? : waterfox](https://www.reddit.com/r/waterfox/comments/d7lu87/webgl_2_support_or_how_to_enable/)
