### ISSUE TITLE
Um OPERA GX Browser problem

### ISSUE THREAD

**Issue by JustCamTro** [magcius/noclip.website#174]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Win64?
What **GPU and Driver Version** are you using?
Uhh what is it
What **Browser and Version** are you using?
Opera GX Browser
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/16395643/68914535-e3cc6480-072c-11ea-8936-f2cb0304e66e.png)

**Comment by magcius** [comment]
> Google SwiftShader

This means you are not using hardware acceleration. Please check your browser settings to ensure that hardware acceleration is enabled.
