### ISSUE TITLE
Doesn't work with Chrome on an older MacBook Pro

### ISSUE THREAD

**Issue by jamesmtbkr** [magcius/noclip.website#18]
I have hardware acceleration enabled in Chrome Version 72.0.3626.119 on macOS High Sierra (10.13.6).  WebGL Report states that 2.0 is support (with a "Major Performance Caveat").  When I try to load noclip.website I get:

"This application requires hardware acceleration to be enabled.
Please enable hardware acceleration in your's browser settings."

If I Enable the "Override software rendering list" flag WebGL Report states "This browser supports WebGL 2, but it is disabled or unavailable."  When I try to load the site I get:

"Your browser does not appear to have WebGL 2 support."

It is an older MacBook Pro (Early 2011) with Intel HD Graphics 3000 512 MB.  Is there a known workaround or am I out of luck on a box this old?

**Comment by magcius** [comment]
Unfortunately, as I can't debug this hardware, it sounds like you're out of luck for now. Sorry :(

**Comment by Flaeki** [comment]
I have the same model and mac os but with the AMD Radeon HD 6750M 1024 MB graphics card.

It also does not work for me :(

Too sad, I really wish to visit your site!

**Comment by magcius** [comment]
Closing as I will probably never support configurations that do not support hardware-accelerated WebGL2. If you find any more information on your specific hardware, please let me know.
