### ISSUE TITLE
Vertex colors aren't working properly for Paper Mario: TTYD

### ISSUE THREAD

**Issue by 100thCoin** [magcius/noclip.website#181]
This seems to be something with the new build. I'm mostly looking at the Mario's House scene, but the vertex colors seem to be completely missing in every scene. On top of this, most 2d sprites like the bushes, leaves, and foliage are no longer visible.

**Comment by magcius** [comment]
Oops. Fixed in 59d125e86c289de0010bb684ca82fe5b32103bb7. Should be live in 5 minutes or so.
