### ISSUE TITLE
Navigation for touch-screen devices

### ISSUE THREAD

**Issue by davebiffuk** [magcius/noclip.website#19]
Maybe I'm missing something obvious but there doesn't seem to be a way to navigate around the world model when using a touch-screen device.

The models load fine on my Pixel 2 (latest Android and stable Chrome) but there's no keyboard or mouse so... no movement - the camera can't be moved. Swiping/tapping does nothing. Is it possible to implement drag-to-move or similar?

Thanks!

**Comment by magcius** [comment]
The site was never developed for mobile. I don't have any mobile devices to develop on, so I wouldn't be able to do it, but you are more than welcome to if you want to contribute.

**Comment by davebiffuk** [comment]
Understood. Thanks for the clarification. I don't think I have the skills to do this sadly but hopefully someone else will step up.

**Comment by MesaBlack** [comment]
looked upon this.

My plan:
same touch navigation as google earth.

**Comment by MesaBlack** [comment]
actually shall we close this? my chromebook has a touchscreen and I noticed its touch nav is alright.

**Comment by magcius** [comment]
beholdnec contributed some touch controls since this issue was opened. I think this is OK now, though the UI side could use some improvement. I'll close for now.
