### ISSUE TITLE
WebGL error

### ISSUE THREAD

**Issue by ToruTheRedFox** [magcius/noclip.website#191]
I'm using Windows 7 Ultimate,
GPU is Intel HD Graphics 4000, latest driver version to get released by Intel
and Chrome 79.0.3945.79
attatched saved html of webgl report because I can't screenshot the full thing (dpi is too small for it to be legible at a scale where the whole page fits in the shot)
[noclip.website webgl report.zip](https://github.com/magcius/noclip.website/files/3984585/noclip.website.webgl.report.zip)

**Comment by magcius** [comment]
Sorry for the delay here. It seems your GPU is reporting a Max Samples of 0, which is bizarre. noclip currently requires multisampling to function, though I might fix this in the future. Sorry about the mess.

**Comment by ToruTheRedFox** [comment]
alright
