### ISSUE TITLE
Uncaught TypeError causing page to not render

### ISSUE THREAD

**Issue by zefreak** [magcius/noclip.website#2]
When I try to view using the following link https://magcius.github.io/model-viewer/ I am getting a blank page with the following console error:

Uncaught TypeError: Cannot read property 'createFramebuffer' of null
    at new e (vec2.js:598)
    at new e (gl-matrix.js:16)
    at new t (main.ts:198)
    at Object.parcelRequire.ZCfc../viewer (main.ts:394)
    at u (main.2531187a.js:1)
    at parcelRequire.R8Er (main.2531187a.js:1)
    at main.2531187a.js:1

**Comment by zefreak** [comment]
Chrome Version 64.0.3282.140 64 bit

**Comment by magcius** [comment]
Does this page say you have WebGL 2 support? http://webglreport.com/?v=2

**Comment by zefreak** [comment]
Sorry for the late response, yes it does:

WebGL 2.0 (OpenGL ES 3.0 Chromium)

It says everything is supported (88 of 88 functions)

**Comment by magcius** [comment]
I genuinely don't know what could be causing this, then. From the error message it sounds like WebGL2 isn't working.

**Comment by magcius** [comment]
Hi! Sorry for the long delay. The site has been through a lot of changes since the last post. Feel free to try again. If this is still happening, please reopen!
