### ISSUE TITLE
Noclip.website error

### ISSUE THREAD

**Issue by Gamemodeon123** [magcius/noclip.website#210]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Windows 10 pro 1903(i think)
What **GPU and Driver Version** are you using?
Microsoft Basic Display Drivers Ver.10.0.17134.1
What **Browser and Version** are you using?
Chrome Ver.79.0.3945.88
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/57966219/71647701-ab76ea80-2cc8-11ea-960c-a520c56018dc.png)

**Comment by magcius** [comment]
> Microsoft Basic Display Drivers Ver.10.0.17134.1

This won't work. Please install graphics drivers for your GPU.

**Comment by Gamemodeon123** [comment]
i cant its supposed to be ATI 4200 Radeon but i cant find drivers for my specific card
