### ISSUE TITLE
YAZZMOD LE DEBUT DE UN DEVELAUPEUR DE GENNI LOL

### ISSUE THREAD

**Issue by yazzmod** [magcius/noclip.website#217]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

**Comment by yazzmod** [comment]
YO

**Comment by magcius** [comment]
Sorry, I cannot offer technical support to non-English speakers.
