### ISSUE TITLE
Hardware acceleration on in Opera GX, unrecognized by site.

### ISSUE THREAD

**Issue by Survivalcraftfreak** [magcius/noclip.website#221]
Windows 10 build 18362
NVIDIA GTX 750 TI 26.21.14.4187
Opera GX 64.0.3417.170
![Opera Snapshot_2020-02-01_210550_webglreport com](https://user-images.githubusercontent.com/25420132/73602273-bbd3ec80-4536-11ea-9cbd-1e33b588c499.png)

**Comment by magcius** [comment]
> Unmasked renderer: Google SwiftShader

You are not using hardware acceleration. SwiftShader is the software fallback. Please consult your browser's manual to turn on hardware acceleration.
