### ISSUE TITLE
Website won't let me open it, it sends me here

### ISSUE THREAD

**Issue by TheCyanCreeper** [magcius/noclip.website#222]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? 
Mac OS High Sierra 10.13.6

What **GPU and Driver Version** are you using? 
Intel HD Graphics 3000 512 MB

What **Browser and Version** are you using? 
Google Chrome 79.0.3945.130 (Official Build) (64-bit)

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![Screen Shot 2020-02-02 at 6 24 34 PM](https://user-images.githubusercontent.com/27738773/73619244-bd122180-45e9-11ea-9eef-22a551f05e05.png)

**Comment by magcius** [comment]
You need to turn hardware acceleration on.
