### ISSUE TITLE
Win 10 Chrome with Hardware Acel enabled still doesnt work

### ISSUE THREAD

**Issue by philipbower122** [magcius/noclip.website#227]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? = Win 10 Latest 2020
What **GPU and Driver Version** are you using? 
What **Browser and Version** are you using? = Chrome Latest
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

![image](https://user-images.githubusercontent.com/38558297/74315644-c6c92100-4d6f-11ea-95d3-fc58a37ffa22.png)

**Comment by magcius** [comment]
> Unmasked Renderer: Google SwiftShader

This means you do not have hardware acceleration enabled. Please turn on hardware acceleration in your browser.

**Comment by philipbower122** [comment]
It is on. i have check it over and over again.
