### ISSUE TITLE
WebGL2

### ISSUE THREAD

**Issue by NeoMicaelHD** [magcius/noclip.website#231]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 7 Ultimate Service Pack 1
What **GPU and Driver Version** are you using? Pentium Dual-Core 6.1.7600.16385
What **Browser and Version** are you using? Google Chrome 80.0.3987.106
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![Sin título](https://user-images.githubusercontent.com/61159901/74677213-7cdca280-5196-11ea-8187-fbb0b638361f.png)

**Comment by magcius** [comment]
You have not enabled hardware acceleration on your browser.
