### ISSUE TITLE
SFA: Missing geometry sometimes occurs

### ISSUE THREAD

**Issue by beholdnec** [magcius/noclip.website#235]
Sometimes, when loading a Star Fox Adventures map, there are missing polygons. This is visible as holes in the landscape geometry. These polygons can sometimes be made to appear by reloading the page.

This is difficult to debug as no error is thrown when this happens. Some part of the graphics system is failing silently.

**Comment by beholdnec** [comment]
Images of the bug:

Before refresh:
![holes-in-geom](https://user-images.githubusercontent.com/9994394/74904916-e4931900-5361-11ea-9dee-495d450e481f.png)
After refresh:
![after-refresh](https://user-images.githubusercontent.com/9994394/74904948-ee1c8100-5361-11ea-8bd0-b0d7329a5daa.png)

**Comment by magcius** [comment]
The difference here seems to be whether I load into maps or not, and it's all in the SFA code. If I load directly into ThornTail Hollow, then:

```
> main.scene.blockCollections[12].blockRenderers[1].models.length
7
```

If I first load into Dragon Rock, and then select ThornTail Hollow from the menu, I get:

```
> main.scene.blockCollections[12].blockRenderers[1].models.length
2
```

Something in the way you're parsing or loading models is order-dependent.

Not a graphics issue.

**Comment by magcius** [comment]
Oh, I think I see the issue. I'll fix.
