### ISSUE TITLE
Continued from last issue.

### ISSUE THREAD

**Issue by philipbower122** [magcius/noclip.website#240]
I checked HA. over and over again and it was turned on. But I am in college. Do you think they could of blocked it from their end?

**Comment by magcius** [comment]
Not sure what to tell you. "Google SwiftShader" is a software fallback. Perhaps `chrome://gpu` would have more information as to why Chrome thinks it needs the software fallback.

**Comment by philipbower122** [comment]
What browser should i use

**Comment by magcius** [comment]
Google Chrome should work, but you need to do a bit of debugging to figure out why you aren't getting hardware acceleration. As I said before, `chrome://gpu` should contain some debugging logs at the bottom that might help you get closer to figuring out the issue.

You could also try using Firefox or Edge.
