### ISSUE TITLE
It cannot open the file

### ISSUE THREAD

**Issue by jagrct3** [magcius/noclip.website#26]
I want to enter to the page and it says thet i need hardware acceleration but i have it aqctivatet. i hope thet you can solucionate my problem thanks

**Comment by magcius** [comment]
What OS, browser, and GPU are you using? Can you take a screenshot of http://webglreport.com/?v=2 ?

**Comment by magcius** [comment]
Closing since reporter provided no information. Please reopen once information is provided.
