### ISSUE TITLE
noclip.website isn't working

### ISSUE THREAD

**Issue by Yoshomay** [magcius/noclip.website#261]
I'm using the newest version of Windows 10 pro x64
I have the Mobile Intel 4 series Express Chipset Faimly (Microsoft corperation - WDMM 1.1) gpu
I am using the newest version of Google Chrome
https://user-images.githubusercontent.com/62309196/76899885-9a646100-6855-11ea-8478-7d41d522c860.png

**Comment by magcius** [comment]
It sounds like your graphics card might be too old, unfortunately. There might be a flag somewhere in chrome://gpu to force WebGL 2 on, but I cannot offer support.

**Comment by Yoshomay** [comment]
ok, thanks.
