### ISSUE TITLE
Katamari Damacy

### ISSUE THREAD

**Issue by Trahald82** [magcius/noclip.website#263]
Hi, sorry if this isn't the right place to ask, but I'd be very grateful if someone could instruct me on how to extract the data from Katamari Damacy's .bin files, thanks!

**Comment by magcius** [comment]
[unpack.py.txt](https://github.com/magcius/noclip.website/files/4346156/unpack.py.txt)

**Comment by magcius** [comment]
Here's the script I found lying around to get the file data. It was written by a combination of Murugo and umbreon.

**Comment by Trahald82** [comment]
Hi again, sorry to bother you once more!
First off, I'd like to thank you for answering my request, it's really appreciated.
However, I'm experiencing difficulties extracting the content of these files.
When executing the command python unpack.py, a long list of files rapidly scrolls by concluding with the message "Done! Exported a total of 2202 files.", but the output folder only contains two .csv files and several empty sub-folders.
Could you please tell me what I'm doing wrong, thanks!

**Comment by magcius** [comment]
It seems the call to `extract` is commented out. Not sure why. Just uncomment line 231.

**Comment by Trahald82** [comment]
Thanks, I finally managed to extract the content of the .bin files, but I'm not sure how to deal with the resulting smaller .bin files, so I'm afraid I must once again require your assistance.

**Comment by magcius** [comment]
Those bin files are what are loaded into noclip. See the Katmari code for reference: https://github.com/magcius/noclip.website/tree/master/src/KatamariDamacy

**Comment by Trahald82** [comment]
I see.
As I'm sure you've figured by now, I'm clueless when it comes to this stuff.
I've only managed to get this far by following your guidance, so could you please instruct me on how to extract the meshes and textures from the .bin files?
Thank you!
