### ISSUE TITLE
noclip.website isn't working on Ubuntu 19.04

### ISSUE THREAD

**Issue by GuilhermeMatheus** [magcius/noclip.website#266]
Hi! I'm receiving this error when trying to access [noclip.website](https://noclip.website/):

```
This application requires hardware acceleration to be enabled.

Please enable hardware acceleration in your's browser settings.

If you have enabled hardware acceleration and are still getting this error message, please open a GitHub issue with as much as information as possible.

Thanks, Jasper.
```
OS: Ubuntu 19.04
GPU: GeForce GT 710, nouveau
Browser: Chrome/79

![image](https://user-images.githubusercontent.com/8089286/77260373-4ea32480-6c66-11ea-9e90-5e3ed990532a.png)

**Comment by magcius** [comment]
"Renderer: Google SwiftShader" means that Chrome is not using hardware acceleration. Please check your browser's settings and make sure that hardware acceleration is turned on.
