### ISSUE TITLE
Noclip.website hardware acceleration

### ISSUE THREAD

**Issue by oof-csm** [magcius/noclip.website#267]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10
What **GPU and Driver Version** are you using? intel hd graphics 4000
What **Browser and Version** are you using? latest chrome version
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![Capture](https://user-images.githubusercontent.com/62533681/77284071-36ea9100-6ca4-11ea-984c-8baa49a87858.JPG)

**Comment by magcius** [comment]
That is not a screenshot of http://webglreport.com/?v=2.
