### ISSUE TITLE
Does not support single-sampled environments

### ISSUE THREAD

**Issue by rcornea** [magcius/noclip.website#271]
**OS and Version**
Windows 7 Ultimate, Service Pack 1
**GPU and Driver Version**
Intel HD Graphics 4000 GPU, driver version 10.18.10.5059
NVIDIA NVS 5200M GPU, driver version 21.21.13.7654
**Browser and Version**
Mozilla Firefox 74.0 (64-bit)

**screenshot of http://webglreport.com/?v=2**:
![image](https://user-images.githubusercontent.com/6632863/77645617-e8b2e780-6f5a-11ea-874c-f775ffbe0ca4.png)

**Comment by rcornea** [comment]
looks like a similar issue to https://github.com/magcius/noclip.website/issues/191

**Comment by magcius** [comment]
Indeed. The issue here is that noclip does not support single-sampled environments. I might lift this restriction one day.

**Comment by magcius** [comment]
Leaving open and retitling to add support for single-sampled environments.

**Comment by magcius** [comment]
I added support for single-sampled environments with optional FXAA.
