### ISSUE TITLE
403 errors on requesting the level assets

### ISSUE THREAD

**Issue by wpw** [magcius/noclip.website#28]
Trying to load any of the models throws a 403 error from Google Cloud Storage.

ex. GET https://storage.googleapis.com/znoclip/z.noclip.website/j3d/ww/Stage/sea/Room44.arc 403

responds with:
`<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to znoclip/z.noclip.website/j3d/ww/Stage/sea/Room44.arc.</Details></Error>`

**Comment by wpw** [comment]
Nevermind, just saw that this is due to bucket migration here https://github.com/magcius/noclip.website/pull/20#issuecomment-467978019

closing since it's expected and should resolve itself

**Comment by magcius** [comment]
Yeah, sorry, the site is currently undergoing maintenance. Apologies for the disruption. I hope it can be over soon.

**Comment by magcius** [comment]
The first stage of data migration is complete. Not all games work yet (had to restore from an older backup), and it'll be a bit slower than before. Hopefully we'll be able to improve things soon.
