### ISSUE TITLE
Wind Waker maps are not found

### ISSUE THREAD

**Issue by rjfranco** [magcius/noclip.website#29]
When attempting to view wind waker maps, a 404 error is produced:

<img width="1263" alt="screen shot 2019-02-27 at 2 54 29 pm" src="https://user-images.githubusercontent.com/272624/53528868-ba38b380-3a9f-11e9-8835-777f42605796.png">

I tried guessing what the correct paths for these resources are with no luck

**Comment by magcius** [comment]
Known issue with the new storage. We're currently working on migrating.

**Comment by magcius** [comment]
This should be fixed now.
