### ISSUE TITLE
[Feature Request] Allow playing compatible animations on dragged models

### ISSUE THREAD

**Issue by SuperHackio** [magcius/noclip.website#294]
Being the accurate render engine that noclip.website is, it would be useful to some communities if we could use the site for previewing custom models. This in itself is a feature already via Dropped Files, however, we cannot play any of the models animations. It would probably work something like "you drag the main model in first, then drag the animation afterwards". You'd just need to make sure that the animation can be played by the model (ex: The model has the correct amount of bones)

As a Super Mario Galaxy hacker, I'm hoping that the J3D System can get these updates soon (you know, assuming you decide to implement this feature. lol).

**Comment by magcius** [comment]
Some form of animation viewer might be nice, however I don't want to commit to support for previewing custom models. I already attempt to support custom Mario Kart tracks, but community tooling is incredibly broken and many levels do not load.

So I don't intend to support this any time soon, sorry.
