### ISSUE TITLE
pale moon support

### ISSUE THREAD

**Issue by Brian151** [magcius/noclip.website#295]
at least the last time i checked, this does not work on pale moon. in theory, it should, because pale moon is a fork of firefox, it just removes/reverts/ignores most of the anti-user/anti-developer junk mozilla added. 

i suspect what's going on is browser-based "feature detection" , which is actually wrong. i know this browser generally can do most HTML5/CSS3/WEBGL stuff...

**Comment by magcius** [comment]
I do not do anything of the sort. If the site does not work on Pale Moon, it is because Pale Moon does not support APIs that I use.
