### ISSUE TITLE
Assert fail in ttyd/rsh_05_c

### ISSUE THREAD

**Issue by mariomadproductions** [magcius/noclip.website#3]
Paper Mario: The Thousand-Year Door - some "rsh" maps not loading - I just get a light grey screen in Chrome

**Comment by magcius** [comment]
There is a valid assert fail bug on ttyd/rsh_05_c, so I'm using this bug to track that. Thanks for reporting!

**Comment by magcius** [comment]
The files rsh_05_c and rsh_06_c appear to be unused / cut files which use an older version of the file format. We're still researching the file format of this one.

**Comment by mariomadproductions** [comment]
Oh interesting. I wonder if the game explicitly has support for both formats or it just happens to work with both. Maybe they aren't loaded properly in-game (the unused maps didn't load any interactive objects of any kind when I tried them).

**Comment by magcius** [comment]
The game has version checks for the format in a few places. We think we have a good understanding of what's going on, it will just take me some small amount of time to implement it.

**Comment by mariomadproductions** [comment]
Does the game have used files in both formats?

**Comment by magcius** [comment]
I don't believe so but I haven't finished checking.

**Comment by magcius** [comment]
For now I've removed this map from the list. I haven't had time to implement the old version of TTYD maps, and probably will never get around to it.

**Comment by magcius** [comment]
Surprise! I've implemented this now.
