### ISSUE TITLE
No scrollbar on Chrome / Mac OS X

### ISSUE THREAD

**Issue by AndreasWebdev** [magcius/noclip.website#30]
Hey, I noticed that since the scrollbars on Mac OS are normally not permanent (unlike on Windows), I am unable to navigate through the site in some areas. There are ways to display scrollbars through CSS permanently (by overriding the -webkit-appearance parameter to none within an ::-webkit-scrollbar selector http://jsfiddle.net/jeremy/Eh7xT/342/)

I'd guess that scroll events (like touchpad-scroll) are disabled because of the camera navigation, however this leads to Mac users not being able to scroll through any container at all (this is true for the "Games" section, their sub-sections as well as the main sidebar (scrolling down to "About" when "Games" is already open is impossible).

![image](https://user-images.githubusercontent.com/7365286/53532698-2e9f4100-3af8-11e9-9836-1d00cd0c62e5.png)

![image](https://user-images.githubusercontent.com/7365286/53532747-61493980-3af8-11e9-8139-042fd545c039.png)

**Comment by magcius** [comment]
This is a side effect of the "camera speed slider" change that happened earlier today. We're in the middle of fixing this now. Sorry for the disruption.

**Comment by magcius** [comment]
Should be fixed now. Could you try again?

**Comment by AndreasWebdev** [comment]
I'll retry once I am at home! (ETA: 16 hours from now, 17:00 CET)

**Comment by magcius** [comment]
I'm assuming this now works. Please reopen if not.
