### ISSUE TITLE
Hardware acceleration bug

### ISSUE THREAD

**Issue by Fancy2209** [magcius/noclip.website#311]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Windows 7 32 bits
What **GPU and Driver Version** are you using?
![image](https://user-images.githubusercontent.com/64917206/83548106-be4d4f80-a4f2-11ea-8b79-9b37b346a98b.png)

What **Browser and Version** are you using?
I tried Chrome and Edge, both say I need to activate hardware acceleration who is already on.
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/64917206/83548228-f5bbfc00-a4f2-11ea-85f8-1ba00beff9e3.png)
 Image of what shows up:
![image](https://user-images.githubusercontent.com/64917206/83548327-213ee680-a4f3-11ea-93e9-fd1480b68907.png)
Proof I have hardware accleration on 
![image](https://user-images.githubusercontent.com/64917206/83548372-33208980-a4f3-11ea-85f8-3e53ec3c776b.png)

**Comment by magcius** [comment]
> Renderer: Google SwiftShader

This means that hardware acceleration isn't working. I've heard reports that rebooting your computer, updating drivers, or reinstalling Chrome manages to work. If you want to do some additional debugging, the `chrome://gpu` tab might have some information.
