### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by kauan115** [magcius/noclip.website#312]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/65743644/83666518-6fabbe00-a5a3-11ea-9c78-7587a8edf7d5.png)

**Comment by magcius** [comment]
Please fill in the questions above. Specifically about GPU and Driver Version.

> Renderer: Google SwiftShader

This means that hardware acceleration is disabled. Please try to enable it in your browser's settings. If this still does not work, I have heard reports that rebooting your computer, updating your graphics driver, and reinstalling your browser can work. If you wish to do additional debugging, try entering `chrome://gpu` into your browser and seeing if you can find anything causing Chrome not to use hardware acceleration.
