### ISSUE TITLE
Use 'Pointer Lock' for looking instead of 'Click and Drag'

### ISSUE THREAD

**Issue by sturob** [magcius/noclip.website#313]
Would make using noclip a bit easier on the carpal tunnel tendons. Especially when using a touchpad.

[API ref](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) and [Example](https://mdn.github.io/dom-examples/pointer-lock/).

**Comment by magcius** [comment]
I do though. https://github.com/magcius/noclip.website/blob/master/src/GrabManager.ts#L108-L110

**Comment by magcius** [comment]
Going to close this. I have seen Chrome spuriously reject my pointer lock requests before, so I will assume that is the issue. Feel free to reopen if you want to provide more information.
