### ISSUE TITLE
Hi! I use Windows 7 OS. GPU - Intel i5-3320M (2.60GHz). Browser - Google Chrome (Last version)

### ISSUE THREAD

**Issue by arthurdreamer** [magcius/noclip.website#316]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

**Comment by magcius** [comment]
Please answer the questions in the ticket.
