### ISSUE TITLE
noclip.website isn't working for me

### ISSUE THREAD

**Issue by netraan** [magcius/noclip.website#322]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

macOS 10.13.6 
ATI Radeon HD 4670  Version ???
chrome 83.0.4103.106 are you using?

![Screen Shot 2020-06-19 at 5 34 55 PM](https://user-images.githubusercontent.com/63310498/85187273-3fc31280-b253-11ea-88fc-704f22b46159.png)

**Comment by magcius** [comment]
Please make sure that hardware acceleration is turn on in your browser.

**Comment by netraan** [comment]
it is and its still not working

**Comment by magcius** [comment]
chrome://gpu might provide additional troubleshooting information. Chrome is not using hardware acceleration (you can see "Google SwiftShader" above, that means it's using software rendering)
