### ISSUE TITLE
Wind Waker flags are unstable after pausing

### ISSUE THREAD

**Issue by tromero** [magcius/noclip.website#328]
https://noclip.website/#zww/sea;ShareData=AK|i3UW{;aT&X|O9s4(~-uL3GQ9C/:UrIyqUC/m5WS:$jUvRR99I;EvUl^}!-X

Pause and unpause while the great sea is loaded. The cloth physics for the flags on the corners of the island will become more unstable the longer time was paused.

**Comment by magcius** [comment]
I'm aware. I believe it should cap to a maximum delta time of 5s. Euler integration is unstable at large timesteps, famous problem.
