### ISSUE TITLE
Cant load noclip :(

### ISSUE THREAD

**Issue by movethebongos** [magcius/noclip.website#329]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134

What **GPU and Driver Version** are you using?
NVidia Geforce GTX 1070
Game Ready Driver 451.48

What **Browser and Version** are you using?
Google Chrome
Version 84.0.4147.89 (Official Build) (64-bit)

Please take a screenshot of http://webglreport.com/?v=2 
and paste it here:
![screencapture-webglreport-com-1594813555087](https://user-images.githubusercontent.com/7247809/87541453-93cde500-c6a1-11ea-8efc-315f212a0f7a.png)

**Comment by magcius** [comment]
Sorry for the delay here. Looking at this screenshot, I can't spot an obvious failure. Can you tell me what error you see on the site?
