### ISSUE TITLE
"Hardware acceleration not enabled" error when it is enabled.  W10 2004 + Chrome 83

### ISSUE THREAD

**Issue by superluig164** [magcius/noclip.website#332]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10 2004 (Build # 19041.388)
What **GPU and Driver Version** are you using? GTX 1660Ti (driver version 451.67)
What **Browser and Version** are you using? Chrome 83.0.4103.116
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/13702255/89132645-a9d20700-d4e3-11ea-9ce8-4b856491d6bb.png)
The site doesn't seem to be working - where can I get the information from?

**Comment by magcius** [comment]
Huh, that's bizarre, webglreport.com is working for me?

![image](https://user-images.githubusercontent.com/40890/89132981-ffe78000-d4cc-11ea-8ea8-bfe12df94534.png)

You can try restarting Chrome or your computer, or looking at chrome://gpu for more information. Your machine should certainly be powerful enough to run the site, so I'm guessing Chrome might have hardware acceleration.

**Comment by themikelester** [comment]
Hmm, http://webglreport.com is down for me as well. (I'm in Australia)

**Comment by magcius** [comment]
What about the HTTPS version? https://webglreport.com/?v=2

**Comment by themikelester** [comment]
The HTTPS version works as expected, but unfortunately it looks like the HTTP version is now also working as expected. Looks like it may have been a temporary routing problem?

**Comment by superluig164** [comment]
It's still down for me, but the https version works.  No clue what the hell's going on with them, but here's the info:
![image](https://user-images.githubusercontent.com/13702255/89137705-fda21780-d506-11ea-9ecc-6520c8ba47cb.png)

**Comment by magcius** [comment]
> Unmasked Renderer: Google SwiftShader

This suggests that Google is indeed falling back to software rendering. Do look in settings for hardware acceleration, and if that's already enabled, try restarting Chrome / your computer (yes, I know, but I've heard it's worked for others before).

The logs in chrome://gpu should have more technical information about why Chrome is falling back to software.

**Comment by superluig164** [comment]
I haven't relaunched yet, but I think I found the problem.  #ignore-gpu-blacklist in chrome://flags was set to "disable" rather than "default" or "enable."  I dunno why, I guess I must've toggled it by mistake while messing around in the flags menu.  I'll hazard a guess that was the problem.
