### ISSUE TITLE
Webgl2 supported and graphics drivers updated, whats going on?

### ISSUE THREAD

**Issue by TheDevJoshOfficial** [magcius/noclip.website#342]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Windows 10 1909
What **GPU and Driver Version** are you using?
NVIDIA Quadro K2200, **DRIVER VERSION EDIT** 23.21.13.9256
What **Browser and Version** are you using?
Google Chrome 85.0.4183.102
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![Capture](https://user-images.githubusercontent.com/64989104/93085707-f91f6180-f663-11ea-8e34-f10fdad434a9.PNG)

**Comment by magcius** [comment]
Try looking at chrome://gpu for more information.
