### ISSUE TITLE
Texture and environment practically non-existent!

### ISSUE THREAD

**Issue by Kesington019** [magcius/noclip.website#344]
Hello!
For a few months now, noclip simply does not work for most games and their maps. The maps load, but the whole map, besides from some objects, has turned into a black wasteland. What's weird is that it has worked before for my devices (Chromebook and Intel laptops), but one day it just refused to function and even occasionally crashed my Intel laptop when loading certain maps. Web GL 2.0 has been enabled and I have reset my device multiple times, but it hasn't helped, and I haven't been able to find help online. I hope this issue can be solved, but I understand if it can't be helped.
Thanks for reading!

**Comment by magcius** [comment]
Can you post a screenshot of https://webglreport.com/?v=2 ?

**Comment by Kesington019** [comment]
![Screenshot 2020-09-22 at 7 57 49 PM](https://user-images.githubusercontent.com/66185048/93925373-f250b880-fd0d-11ea-845c-8c6cbe7fbb44.png)

**Comment by magcius** [comment]
PowerVR? I'm likely to blame your GPU and/or drivers. Can you check the Console by hitting F12 when on a noclip site and seeing if there are any warnings or debug output related to WebGL in there?
