### ISSUE TITLE
"This application requires hardware acceleration to be enabled" BUG (hardware acceleration is enabled)

### ISSUE THREAD

**Issue by Hayden-W** [magcius/noclip.website#352]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?

OS and version information: (Basically Windows 10 Home, 10.0.19041 Build 19041)
![image](https://user-images.githubusercontent.com/29484514/95291591-8fd5eb80-08bb-11eb-825b-35bcb8ae6825.png)

What **GPU and Driver Version** are you using?

GPU is a 980Ti, driver version is 456.55, which is latest as of today (7th oct 2020) 

What **Browser and Version** are you using?

Browser is Chrome, here is a screen cap of the version page: 
![image](https://user-images.githubusercontent.com/29484514/95291820-05da5280-08bc-11eb-9495-de3e70321901.png)

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/29484514/95291862-1ab6e600-08bc-11eb-9553-1121ac0cdc11.png)

Happy to help in any way that I can!

**Comment by Hayden-W** [comment]
Interestingly, after downloading and setting up the repo to test on my local machine, opening the project through "regular" chrome still results in the same error, but opening the project through VSCode's chrome debugger does work!
Here's a screencap of debug chromes's version page:
![image](https://user-images.githubusercontent.com/29484514/95294835-b860e400-08c1-11eb-9327-c885a45dbfe6.png)

If I have time I'll keep poking at it and see if I come up with anything.

It's a great project, give me a shout if I can supply any more info 👍

**Comment by PFedak** [comment]
Can you double check that you've enabled hardware acceleration in Chrome's settings? It's under advanced->system, or just search for hardware. The screenshot you posted definitely says it's using a software implementation.

**Comment by magcius** [comment]
Yes, for whatever reason, Chrome has decided to use software rendering. You can try enabling chrome://flags/#ignore-gpu-blocklist . The log in chrome://gpu/ should have the reason why it was disabled.

I've also seen it be because of a transient error for a session -- try restarting your browser, and your computer. That can help reset it.

**Comment by Hayden-W** [comment]
Ok cool,
Hardware acceleration was definitely enabled (Would have been mortified if that was the case aha)
Enabling "ignore-gpu-blocklist" has done the trick!

Thanks for the help! 👍
