### ISSUE TITLE
noclip.website not working

### ISSUE THREAD

**Issue by Adamillo** [magcius/noclip.website#359]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Windows 8. Service Pack 1 64 bit version
What **GPU and Driver Version** are you using?
I tried to fix the graphical issues I've had with my Intel(R) HD Graphics 4000 by changing it to the NVIDIA GeForce GT 71 0M GPU, but now now I'm getting the "This application requires hardware acceleration to be enabled" error even though I already enabled this feature on my browser. The driver version for the Intel(R) HD Graphics 4000 GPU is 9.17.10.3114 and for the NVIDIA GeForce GT 710M GPU the driver version is 21.21.13.7654
What **Browser and Version** are you using?
The Browser is Opera and the version is 65.0.3467.78
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![Unbenannt](https://user-images.githubusercontent.com/45568316/96334213-534e8080-106f-11eb-9134-239dd4dfa9e0.PNG)

**Comment by magcius** [comment]
Sorry for the late reply

> Unmasked Renderer: Google SwiftShader

This means that your computer is not using your GPU. Try restarting Google Chrome or rebooting your computer. If that does not work, you can always try checking the logs at the bottom of `chrome://gpu` to get more detailed information about what might be going wrong.
