### ISSUE TITLE
Noclip doesn't work even though hardware acceleration is turned on like the site asked me to.

### ISSUE THREAD

**Issue by ZachmanAwesomeness** [magcius/noclip.website#363]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
I am using Microsoft Windows 10.
What **GPU and Driver Version** are you using?
I have the latest GPU and AMD Quad Processor versions.
What **Browser and Version** are you using?
I am using the latest version of Google Chrome.
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/73263225/96805439-aca41000-13df-11eb-9e20-8784acbb327e.png)

**Comment by magcius** [comment]
Please take a screenshot of http://webglreport.com/?v=2 and paste it here.
