### ISSUE TITLE
noclip website issue

### ISSUE THREAD

**Issue by nttain** [magcius/noclip.website#366]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10
What **GPU and Driver Version** are you using? Nvidia 1080
What **Browser and Version** are you using? CHROME
Please take a screenshot of http://webglreport.com/?v=2 and paste it here: ![Screenshot from 2020-10-24 22-20-15](https://user-images.githubusercontent.com/73411235/97096776-225de500-1647-11eb-8f86-f8430a5d601c.png)

**Comment by magcius** [comment]
Sorry, the link was broken. Can you take a screenshot of https://webglreport.com/?v=2 ?
