### ISSUE TITLE
noclip.website not loading even with hardware acceleration turned on

### ISSUE THREAD

**Issue by ZachmanAwesomeness** [magcius/noclip.website#369]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Windows 10
What **GPU and Driver Version** are you using?
Not sure but version is latest
What **Browser and Version** are you using?
Latest version of Google Chrome
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/73263225/97936022-4ce72680-1d48-11eb-8d4e-336130e9af5c.png)

**Comment by magcius** [comment]
> Unmasked Renderer: Google SwiftShader

This means you're using software rendering. I've heard that restarting your browser or computer can help "reset" it. If you want to dig into the reason Chrome isn't using hardware acceleration, going to `chrome://gpu` should help.
