### ISSUE TITLE
noclip Report

### ISSUE THREAD

**Issue by TheLuckiestKID2010** [magcius/noclip.website#372]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10 Pro 2004 x64
What **GPU and Driver Version** are you using? Cannot find out, processor: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz  2.50 GHz 
What **Browser and Version** are you using? Microsoft Edge version 86.0.622.63
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![report](https://user-images.githubusercontent.com/74104258/98443683-ca25e900-2104-11eb-8d0c-a9f787c00748.jpg)
![report2](https://user-images.githubusercontent.com/74104258/98443685-ceea9d00-2104-11eb-90f2-f59b743c4feb.jpg)

**Comment by magcius** [comment]
WebGL 2 seems to be unavailable. I cannot help you figure out why -- you can try a different browser.
