### ISSUE TITLE
noclip.website not working

### ISSUE THREAD

**Issue by Akulfo** [magcius/noclip.website#373]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 7 Ultimate Service Pack 1 64-bit
What **GPU and Driver Version** are you using? AMD A4-6300 APU with Radeon(tm) HD Graphics 
What **Browser and Version** are you using? Google Chrome 86.0.4240.183
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/74247771/98679890-69362500-233f-11eb-92d7-6123b6945840.png)

**Comment by magcius** [comment]
> Unmasked Renderer: Google SwiftShader

This means hardware acceleration is not working. Please make sure it's enabled in the settings, or try restarting your browser and computer.
