### ISSUE TITLE
Windows 10 1900 version (i think) I have an Intel HD Graphics Card and i don't know which driver im using but it's the latest im using Google Chrome Version 86.0.4240.198 Noclip.website say's that my browser don't support webGL 2 but webGL report say's that my browser support it. please help

### ISSUE THREAD

**Issue by Hermes0123** [magcius/noclip.website#378]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:

**Comment by magcius** [comment]
Please post the screenshot of webglreport.com here.
