### ISSUE TITLE
I

### ISSUE THREAD

**Issue by TailGames** [magcius/noclip.website#380]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:

I am using Windows 7 Professional.
I am using a GTX 9600 because memories and other reasons.
I am using the latest version of Chrome.

**Comment by magcius** [comment]
Please post a screenshot.
