### ISSUE TITLE
J3D BRK non-clamped color animation problem

### ISSUE THREAD

**Issue by Wexos** [magcius/noclip.website#382]
In [my fork](https://github.com/Wexos/noclip.website) I spawned object signal1 from Patapata.arc (Mario Kart Double Dash), and also loaded the BRK animation, and it looks incorrect. The problem comes from the colors going both negative and above 1.0/255 (see curve). In J3DGraphBase.ts there is a clampTo8Bit function, but this only makes sure it's not negative. Actually clamping it between [0.0, 1.0] fixes the problem. However, this might cause other problems. While constant color registers should be clamped, the color registers should not be clamped. They can be values outside [0.0, 1.0].

![BRK curve.](https://user-images.githubusercontent.com/29820962/103367143-9fcd2800-4ac4-11eb-8816-3592aaee91cb.png)
![signal1 object from Mushroom City.](https://user-images.githubusercontent.com/29820962/103367539-a4461080-4ac5-11eb-9c6d-4ccdbb652bfc.png)

**Comment by magcius** [comment]
I was curious about this, because I didn't know if the original game would overflow or not. I suspect there's an explicit clamp in there now, but let me triple-check and get back to you.

**Comment by magcius** [comment]
Just confirmed

J3DAnmTevRegKey::getTevColorReg clamps to -1024.0...1024.0
J3DAnmTevRegKey::getTevKonstReg clamps to 0...1

I'll fix this shortly
