### ISSUE TITLE
SFA: Krazoa Palace floor reflection freezes when window is resized

### ISSUE THREAD

**Issue by beholdnec** [magcius/noclip.website#396]
The floor reflection in Star Fox Adventures' Krazoa Palace freezes when the window is resized. This effect makes use of the temporal texture, a copy of the previous frame, to draw inverted on floor polygons. When the window is resized, the temporal texture no longer updates.

This issue possibly affects other games that use the temporal texture.

**Comment by magcius** [comment]
Same with the Temporal Texture in Katamari. I suspect my recent optimization to GfxrRenderGraph in commit f2467e7cfccbf7645fa8eddbfa671f4a1116e20d is to blame.
