### ISSUE TITLE
noclip.website says my browser has a non-functioning version of WebGL 2 that has not been seen before.

### ISSUE THREAD

**Issue by DerpTaco99921** [magcius/noclip.website#404]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10
What **GPU and Driver Version** are you using? Intel HD 4000 10.18.10.4425
What **Browser and Version** are you using? Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/60769253/112724565-58e7a680-8eea-11eb-8a8e-e835aa8337b1.png)

**Comment by magcius** [comment]
Can you go to the noclip error page, hit F12, and type in the console: `gl.getInternalformatParameter(gl.RENDERBUFFER, gl.DEPTH32F_STENCIL8, gl.SAMPLES)` ?
