### ISSUE TITLE
Project dependencies aren't listed

### ISSUE THREAD

**Issue by BryceBarbara** [magcius/noclip.website#405]
It seems that this project requires rustup to be installed in order for this thing to be built. If you'd like to make this project more friendly to new devs, it might be good to list dependencies in the README.md. 

It would also be nice to have a **Getting Started** section in the readme but that might be more work.

**Comment by magcius** [comment]
I try to get contributors to join the Discord Server, where I have a Getting Started guide, where I can help people individually if needed. The README mentions this.

**Comment by BryceBarbara** [comment]
It's great that you have an area for a dev community to discuss stuff! Having a getting started guide in source control is really handy. Not only is everything in one place (the repository), but you also get a change history for the guide. 

That's helpful when you want to know how things were done a long time ago. If you vanished and new developers were trying to figure out what the process was a while back, they couldn't without the history. 

🤷‍♂️ Just my two cents.
