### ISSUE TITLE
Starfox Adventures, Krazoa Shrine (Scales Encounter) 

### ISSUE THREAD

**Issue by JosephMPMaher** [magcius/noclip.website#409]
For some odd reason some of the maps from the Krazoa shrines won't seem to load up, All I would see is a black screen. Anything I should know about?

**Comment by magcius** [comment]
It seems like it's crashing because `nwshrine/ANIM.BIN` / `nwshrine/ANIM.TAB` doesn't exist. @beholdnec ?

**Comment by beholdnec** [comment]
I have uploaded some files. A couple Krazoa shrine maps still fail to load. I will investigate later.

**Comment by beholdnec** [comment]
Fixed.
