### ISSUE TITLE
Portal (first one) has issues caused by expensive water

### ISSUE THREAD

**Issue by stopmotio** [magcius/noclip.website#413]
Few months ago water looked perfect. Expensive water was added, creating weird white shines that were not present in the original. Should be easy, but code has a way of being exactly the opposite of how one expects. Disabling expensive water in modern builds fixes, so should just disable upon loading portal 1 maps.

**Comment by magcius** [comment]
Can you give a share link for where you see the issues with the water? I checked the water at the beginning of escape_02 and could not spot it.

**Comment by stopmotio** [comment]
It's likely less obvious in the escape because it's closer to the water color. Try testchmb_a_07

**Comment by magcius** [comment]
Looks mostly the same to me? The general palette is brighter in the actual Portal client (possibly missing a tonemapping?), and it seems like the envmap is brighter, but I don't see "white shines" like you're suggesting.

![image](https://user-images.githubusercontent.com/40890/119527841-8f4c7100-bd35-11eb-9498-e0e67e89e1ff.png)

**Comment by magcius** [comment]
Note that this isn't surface isn't water (it's actually a lightmappedgeneric), and thus shouldn't have changed with the introduction of expensive water. But if you suspect something, can you check if changing the "Use Expensive Water" checkbox in the Render Hacks panel on the left fixes things for you?

**Comment by stopmotio** [comment]
Huh I was sure it didn't use that. Disabling expensive water via checkbox made it darker and shineless which was what I _thought_ it was supposed to look like. I guess I'm wrong. Sorry.

(are you using the openGL renderer on Portal? I played on Windows via DirectX awhile back and could've sworn I saw no shine there)

**Comment by magcius** [comment]
I'm using the official Portal Windows client from Steam, which uses DX9. My graphics settings are as follows:

![image](https://user-images.githubusercontent.com/40890/119529801-47c6e480-bd37-11eb-86a5-f4008e925908.png)

Which is a rough approximation of what the noclip renderer is trying to emulate.

**Comment by stopmotio** [comment]
Does it change if you set water to "reflect all"? "Reflect world" is based off the DX8 version which uses a completely different material in the VPK files IIRC.

**Comment by stopmotio** [comment]
Ok I looked it up and [according to the Valve Developer Community](https://developer.valvesoftware.com/wiki/DirectX_Versions#DirectX_8.0) there is a DX8 water shader with reflections but it is sparingly used. I can't find any info about "reflect world" vs "reflect all" though

**Comment by magcius** [comment]
That determines whether entities are rendered into reflections too, rather than just BSP geometry, I believe.

**Comment by magcius** [comment]
I fixed the remaining discrepancy with water reflections appearing dark in commit 80d01f0a4875c3083f116557e4858154493c9daa.

![image](https://user-images.githubusercontent.com/40890/119533894-2a941500-bd3b-11eb-802f-db35407c635b.png)

**Comment by stopmotio** [comment]
I only have access to my school chromebook right now, what does it look like when you type `mat_dxlevel 80` into the console?

**Comment by magcius** [comment]
I still see specular reflections, though they are much less bright.

![image](https://user-images.githubusercontent.com/40890/119539567-2bc84080-bd41-11eb-9399-eb01e0edf7dd.png)

**Comment by stopmotio** [comment]
Okay that confirms it's not planar reflections.

Thanks for everything! Someday I'll make a PR that's actually worthy of this project.

**Comment by magcius** [comment]
I would not put it past the Source Engine to have other possible differences here, so please do re-test on your own when you get a chance and verify the results.

**Comment by stopmotio** [comment]
Okay, guess who got around to checking on my end. This was a fresh install, I haven't played the first since I was running out of space.

![comparison_shot](https://user-images.githubusercontent.com/21047900/120047090-af07c180-bfe1-11eb-9929-c78a7b70390a.jpg)

In conclusion, everything is good. No idea why DX8 is so dark.

**Comment by magcius** [comment]
I believe DX8 uses completely different materials. Thank you for double checking! Please file more bugs if you spot any other discrepancies.

**Comment by stopmotio** [comment]
> I believe DX8 uses completely different materials. Thank you for double checking! Please file more bugs if you spot any other discrepancies.

Oh unrelated but I did some digging and I found some files
``` 
shaderapidx9.dll
shaderapiempty.dll
```
No dx8. So that could be it, maybe.

**Comment by magcius** [comment]
That's less relevant than you think. If you're interested in the exact details, I can explain them to you on Discord lol, not too interested in a back and forth on GitHub here
