### ISSUE TITLE
Skybox render issue on GTA maps

### ISSUE THREAD

**Issue by alexkaessner** [magcius/noclip.website#418]
Hi, I’ve noticed that _all_ the GTA maps all have some issues with the skybox. As you can see in the attached screenshots & GIF looking up to the sky reveals some water. Though strangely it’s cut off and also flipped in to the camera movement (see GIF).

![GTA 3 Glitch](https://user-images.githubusercontent.com/6615076/126352847-cc516bed-9758-4ec3-9f54-bf23a6b5d4f6.gif)
![GTA San Andreas](https://user-images.githubusercontent.com/6615076/126353326-258e4955-8b5b-489a-a8ce-d01d02015371.png)
![GTA Vice City](https://user-images.githubusercontent.com/6615076/126353363-b69638c6-1eba-40da-b16d-e13d401e113f.png)
![GTA 3](https://user-images.githubusercontent.com/6615076/126353373-8efa860d-d83f-4a08-bf14-cc308316c87d.png)

### System
macOS 11.4
Google Chrome 91.0.4472.164

**Comment by magcius** [comment]
Yeah, there's likely something weird going on here. I don't know if @davidar is still planning to maintain the GTA renderer, but if they're not, I can try to take a look and figure out the issue.

**Comment by magcius** [comment]
I took out the false water plane in be36f0416c312e0a2a5900f97e408e49bf6c86dd which is not ideal but should help improve the look of things. Will need to work through the math if I want to solve this.

**Comment by magcius** [comment]
Considering this solved for now. I might look at this again at some point in the future.

**Comment by davidar** [comment]
Hm, I'm assuming something changed at some point with [the camera matrices](https://github.com/magcius/noclip.website/blob/be36f0416c312e0a2a5900f97e408e49bf6c86dd/src/GrandTheftAuto3/render.ts#L637-L643)? I'd also have to dig into it to figure out what's going wrong, haven't had a chance yet.

**Comment by magcius** [comment]
The issue might actually be that in commit 627cd9b62bf25c984903326f5eb0e2ed988a90a7 I changed the sign of the near and far camera frustum parameters, which is probably what broke things. The matrix itself didn't change though, only the near / far fields of the frustum. I should probably double-check that removing the negations is correct, since I also didn't adapt the Wind Waker code for it, though I'm quite sure it is.

**Comment by davidar** [comment]
Ah, yes, that would do it. No idea which is correct, but the GTA sky shader does depend on the sign of the near field, so adding in a negation on that parameter should fix things (though I don't have a dev environment set up for noclip at the moment to check)
