### ISSUE TITLE
noclip.network is not working and hardware acceleration is enabled

### ISSUE THREAD

**Issue by personpermin** [magcius/noclip.website#42]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2
 and paste it here: 
![image](https://user-images.githubusercontent.com/48333158/53998544-f5b52c80-40f4-11e9-9248-2885b8549b4d.png)

**Comment by magcius** [comment]
What's not working?

**Comment by magcius** [comment]
Please reopen when needed information is provided.

**Comment by personpermin** [comment]
nothing now i'm sorry for wasting your time
