### ISSUE TITLE
This is the error message received from loading website 

### ISSUE THREAD

**Issue by FukAwf** [magcius/noclip.website#420]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:

**Comment by magcius** [comment]
Please answer the questions in the form.

**Comment by FukAwf** [comment]
× This browser supports WebGL 2, but it is disabled or unavailable.

Sometimes this is the result of older video drivers being rejected by the browser. Try updating your video drivers if possible.

Also check out Get WebGL, or try installing the latest version of Chrome, or Firefox.
