### ISSUE TITLE
Error On Website "noclip.website"

### ISSUE THREAD

**Issue by DoritosOff** [magcius/noclip.website#423]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? I'm using Windows 10 
What **GPU and Driver Version** are you using? 
![image](https://user-images.githubusercontent.com/88293061/127786916-02fa3929-46e4-4bc7-ba9d-e5cfd57b804d.png)
![image](https://user-images.githubusercontent.com/88293061/127786947-cd0ffd45-6785-4d01-88db-717c6d8c8c89.png)
What **Browser and Version** are you using? Chrome Version 92.0.4515.107 (Official Version) 64 bits
Please take a screenshot of https://webglreport.com/?v=2 and paste it here: 
![image](https://user-images.githubusercontent.com/88293061/127786988-4f434c65-f52c-43c9-8a7d-9f59986c1d13.png)

**Comment by magcius** [comment]
Please try enabling Hardware Acceleration in the settings of your browser. If that does not help, try rebooting your system -- sometimes Chrome disables Hardware Acceleration after it's been running a lot, and a reboot can help clear that up.

**Comment by DoritosOff** [comment]
I'm already tried to do that and still isn't working ;-;. You got any other options, please? (Sorry if it sounds rude, my inglish isn't so good)

**Comment by magcius** [comment]
The information at chrome://gpu might give you some feedback on why Chrome is disabling WebGL 2.

**Comment by DoritosOff** [comment]
Thanks <3
