### ISSUE TITLE
Wind Waker maps are messed up

### ISSUE THREAD

**Issue by Suspicious-Link** [magcius/noclip.website#44]
I'm not sure what's going on, but all of the Wind Waker maps I've tried to load look like this:

![glitched wind waker](https://user-images.githubusercontent.com/48360422/54043646-f647d480-4181-11e9-9921-11a26d8f9e72.PNG)

This didn't happen on any other maps I've loaded, just Wind Waker. Is this something that needs to be fixed?

**Comment by magcius** [comment]
Try force refreshing with Ctrl+F5. I accidentally broke things last night, but they should be fixed now.
