### ISSUE TITLE
a "home release" ??? for videos makers or websites 

### ISSUE THREAD

**Issue by sixcentgeorge** [magcius/noclip.website#454]
recently i found your software ..i like it.. as much as some good old bsp viewer...of half-life...
i want a release to use it at home and make a video of a new "order" of maps in order to create a new mod ..based on hl2 ep 1 ep2 ...  [ i found there is an ep3 out... made by an other jasper [?] i like it spirits of op4...with models.. but for my project i prefer you to imagine fighting monsters and enemies that are in wofenstein 2006.. ][ like in the cavern with eggs .. i see well the monster at the top of the casttle ; in others place most of the time the "men & women in black" ]
i found the topic that i made at synergy steam in march 2015...  named : searching the right way to edit for a change of maps order

https://steamcommunity.com/app/17520/discussions/0/617330406656068742/?tscn=1541180301

i woulsd like to use your tool to create the "new ordered maps order" and record it... i have two card one is a rx480 and a gtx1060 ..so most of the time i record the ati screen or make screen capture of it with the ati tool...that is in the nvidia display screen ..
the change are not so much..but they remove nearly all the famous "sequence scriptings" and the game is more oriented ACTION KILLING...... that negociations.. 
it is a sort of coop ready mod.. with the final maps that are the one from episode 1 in the trainstation.. so the game server launch the mod again by loading the famous hl2 arrival of freeman in a train ...

i do not hope your tool to be able all this "gmod" in the maps... only the maps [ and may be some non moving monsters  like the  aliens of wolfenstein..  to show where i want to use them ; peraps using screen capture made in game of the original wolfenstein]

**Comment by magcius** [comment]
This is likely never going to happen.

**Comment by sixcentgeorge** [comment]
i wonder how you can be so sure about my thing to happen or not..???
i simply have to use the current website and load maps in the order i want and record... as dumb as a sniper of svencoop or some looser from "black mesa"..
i find very cool to see how fast my issue is closed....  there is more dumbass "ruling" for the mod than people at work..here also...dead of laughing on my floor .. try to sleep longer next time
