### ISSUE TITLE
Source Engine: Lightmaps appear to be super broken

### ISSUE THREAD

**Issue by notfrying1pans** [magcius/noclip.website#464]
![image](https://user-images.githubusercontent.com/49667761/137591013-a729ccd2-7165-4ec7-83b4-09df36c23f04.png)

**Comment by magcius** [comment]
I guess Firefox doesn't support EXT_texture_norm16. That seems to be tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1735401

Please use another browser until that extension is supported, I guess. Maybe I will add back an LDR lightmap mode at some point.

**Comment by magcius** [comment]
Oh, I believe you should also be able to enable `webgl.enable-draft-extensions` in about:config, if you want to keep using Firefox.

**Comment by notfrying1pans** [comment]
Enabling it doesn't seem to work. Sad!

**Comment by notfrying1pans** [comment]
Thanks! It seems to work now
