### ISSUE TITLE
Naming Issues and Other Issues

### ISSUE THREAD

**Issue by AlmostTWD98** [magcius/noclip.website#471]
* Some objects appear almost black (e.g. in Mario Kart: Double Dash!!, in Award, the Piantas are black).
* Some objects appear in different spots (e.g. in Mario Kart: Double Dash!!, in Award, Toadsworth is underwater).
* In Mario Kart Wii, _Luigi's_ Circuit _(End_ Credits) should be called _Luigi_ Circuit _(Credits)_.
* Mario Kart _8:_ Deluxe should be called Mario Kart _8_ Deluxe.
* In Mario Kart 8 Deluxe, the first Mario _Circuit_ should be called Mario _Kart Stadium_.
* In Mario Kart 8 Deluxe, _WII_ Moo Moo Meadows should be called _Wii_ Moo Moo Meadows.
* In Mario Kart 8 Deluxe, _WII_ _GrumbleVolcano_ should be called _Wii_ _Grumble Volcano_.
* In Mario Kart 8 Deluxe, _WII_ Wario's Gold Mine should be called _Wii_ Wario's Gold Mine.
* In Mario Kart 8 Deluxe, in Excitebike Arena, the ramps that randomly swap spots don't show.
* In Mario Kart 8 Deluxe, in Excitebike Arena, the oil slicks that randomly swap spots don't show.

**Comment by magcius** [comment]
addressed the naming issues in 84fcbe8eed1e7a642b61e0df63210baea92c699c

probably not going to fix the other issues unless someone contributes a patch

**Comment by AlmostTWD98** [comment]
It still says _Luigi's_ Circuit (Credits) instead of _Luigi_ Circuit (Credits).
