### ISSUE TITLE
What does "loadFlags" in "J3DLoader.ts" do?

### ISSUE THREAD

**Issue by MichaelHinrichs** [magcius/noclip.website#476]
All the other BMD/BDL programs , like J3D Model viewer and superBMD, just skip over those two bytes or name them somthing like "unknown". Even the Mario Kart Hacking Wiki doesn't know that to do with it. It says it's 01 for BMD & 00 for BDL, but that's incorrect.
Wind Waker, and both Mario Galaxy games have BDL files with 00, and Mario Sunshine has BMDs that are 01, but Twilight Princess has BMD files that say 00. BDL playermodels in Wind Waker, and Galaxy have a 02s.

**Comment by magcius** [comment]
It defines the matrix transform setup used by the skeletal animation. There are other bits that can be set (0x100 denotes a model as not being able to animate), but I haven't seen any in the wild.

https://github.com/magcius/noclip.website/blob/8b0de601d6d8f596683f0bdee61a9681a42512f9/src/Common/JSYSTEM/J3D/J3DLoader.ts#L81-L89

**Comment by MichaelHinrichs** [comment]
What about values of 0x00, 0x01, and 0x02?

**Comment by magcius** [comment]
They're listed above. 0x00 = Basic, 0x01 = XSI, 0x02 = Maya.

**Comment by MichaelHinrichs** [comment]
I... don't know what any of those mean.

**Comment by magcius** [comment]
They change how skeleton transforms are calculated. If you don't know what that means, I don't know how else I can help you.

**Comment by MichaelHinrichs** [comment]
I think you are greatly overestimating how smart I am. I apologize if i'v been wasting your time.
