### ISSUE TITLE
Wii U Transfer Tool: Allow camera movement when animation is paused

### ISSUE THREAD

**Issue by ngoomie** [magcius/noclip.website#477]
Looking through the Discord for past conversations about the Wii U Transfer Tool, it's apparently by design that you can't break away from the pre-set camera movements, but regardless I think it'd still be nice to have some way to explore it like you can everything else. (Everything else that I'm familiar with, anyways.)

If it's still not going to be changed though I completely understand! I just thought it might be worth a shot to ask.

**Comment by magcius** [comment]
Thank you for the suggestion; I've implemented it in 692837adf73dc42f9853ed985e1baafc0fa78146.
