### ISSUE TITLE
this website is cringe

### ISSUE THREAD

**Issue by AnErrupTion** [magcius/noclip.website#482]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? doesn't matter
What **GPU and Driver Version** are you using? doesn't matter
What **Browser and Version** are you using? librewolf with webgl disabled
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
doesn't matter

this website is just cringe since it requires webgl. i don't see why websites would need webgl anyway.

**Comment by magcius** [comment]
k
