### ISSUE TITLE
noclip.website not working

### ISSUE THREAD

**Issue by PROOGAMERR83481** [magcius/noclip.website#486]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What Lenovo are you using?
What intel core i5 are you using?
What Microsoft edge are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/96843751/147811579-91101624-4d9a-4c13-a986-92e22b4148b2.png)

**Comment by magcius** [comment]
That is not the requested screenshot.
