### ISSUE TITLE
my noclip.website is not workin

### ISSUE THREAD

**Issue by piotrek117studos** [magcius/noclip.website#487]
Hey!! Me noclip website is nit working. Here are my reasons

Im using Windows 7
Nvida driver. Which is on the hardware tools in the control panel.
Google Chrome Newsest version.

![2022-01-01 14_54_59-Greenshot](https://user-images.githubusercontent.com/85959568/147853374-6f73fe29-f367-4953-aa44-f5fa513fee73.png)

**Comment by magcius** [comment]
Please make sure hardware acceleration is enabled in settings.
