### ISSUE TITLE
Dark Souls maps break site

### ISSUE THREAD

**Issue by Pieplayerian** [magcius/noclip.website#492]
Specifically, any of the Dark Souls maps would break the site. They do not load, and they do not allow other areas in any game on the site to be selected or viewed. A new tab of noclip must be opened to fix this (in my experience). There are no issues with either of the dark souls' collision datas, just the maps.

**Comment by magcius** [comment]
Fidxed by ab9cb1c21d35f47fc63c8247e75506f310e19324.
