### ISSUE TITLE
Assert fail

### ISSUE THREAD

**Issue by j2l** [magcius/noclip.website#50]
It built locally but any map has the error, in FF:
```
assert@http://localhost:1234/main.c39d6dcf.js:354:19
decompress/<@http://localhost:1234/main.c39d6dcf.js:28892:5
util.ts:5:14
Error: Assert fail: 
```
in Chrome:
```
util.ts:5 Error
    at Object.assert (util.ts:5)
    at Yaz0.ts:38
    at async Promise.all (:1234/index 0)
assert @ util.ts:5
util.ts:5 Error
    at Object.assert (util.ts:5)
    at Yaz0.ts:38
    at async Promise.all (:1234/index 1)
assert @ util.ts:5
2util.ts:5 Uncaught (in promise) Error: Assert fail: 
    at Object.assert (util.ts:5)
    at Yaz0.ts:38
    at async Promise.all (:1234/index 0)
```

**Comment by magcius** [comment]
You need to supply the app with data; it does not come with any in the git repo. What game do you want to load?

**Comment by j2l** [comment]
Ah, ok.
I wanted to try any. Whe could I load one?

**Comment by magcius** [comment]
Is there any reason you are using a local version of the app instead of the hosted version? Data can be a bit annoying to fetch, but you can try using SM64DS data. https://cdn.discordapp.com/attachments/551624375875665930/554043370977230849/sm64ds.7z

**Comment by j2l** [comment]
Thank you. I just want to clone and test locally as with other github projects.
Feel free to delete this issue
