### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ThatSamSause** [magcius/noclip.website#505]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![Capture](https://user-images.githubusercontent.com/76608776/159860049-0d5b6cd2-aded-4aec-bc8c-2ed7bc5226b3.PNG)

**Comment by magcius** [comment]
Please answer the provided questions.
