### ISSUE TITLE
Source Engine maps load a white screen on Chromebooks

### ISSUE THREAD

**Issue by slambo311** [magcius/noclip.website#512]
It acts like it's loading (the loading bar moves, the render hacks tab opens up, etc.), but it never actually loads any part of the map, just white. I've been mainly using just regular Chrome. Here's a picture of it, taken from Half-Life 2's background01:
![image](https://user-images.githubusercontent.com/61334045/164090884-42029d3f-5ccd-4d09-8683-4fc3456a94f0.png)
In some games, like Portal 1, Portal 2, and Team Fortress 2, bloom makes the white screen a bit brighter, if it helps.
My theory is that it only affects games that were made in later versions of the Source Engine, since Portal and TF2 both use a newer Source Engine. Half-Life 2 was literally the first Source Engine game, so bloom doesn't do crap. Half-Life 2: Deathmatch and Counter-Strike: Source were literally released the same month as Half-Life 2, so they're also unaffected.

Also, Half-Life 1 renders just fine, most of the time (c1a0 and t0a0 work fine, crossfire's a black screen, that's all I've really tested so far).

**Comment by magcius** [comment]
My main guess is that you're on a Chrome version before 99. Source Engine requires CORS w/ Range without preflight, which is a relatively new feature https://chromestatus.com/feature/5652396366626816

**Comment by slambo311** [comment]
Yeah, I'm on 92. No clue why my Chromebook won't update it.

**Comment by magcius** [comment]
The backend file server has been reconfigured. This should be fixed in both older Chrome and Firefox now.

**Comment by slambo311** [comment]
Alright, it's working pretty well now, other than the lighting.
![image](https://user-images.githubusercontent.com/61334045/164768044-3f183f1a-d53f-45e3-b187-91a24579c48d.png)

**Comment by magcius** [comment]
Weird -- it looks like the lightmaps aren't properly being updated? I would guess that's a GPU / driver bug, but I don't know enough to be sure. Do you know what GPU the hardware is using?

**Comment by slambo311** [comment]
My Chromebook doesn't let me check the GPU for some reason, but here's my CPU: Intel(R) Celeron(R) CPU N3060 @ 1.60GHz (2 threads, 2.48GHz).

**Comment by slambo311** [comment]
Also, the map I screenshotted here, sp_a2_fizzler_intro, has the lights flicker for a few seconds, so that might be another reason. Plus, those lights might use `light_dynamic` or `env_flashlight` entities, instead of `light`, `light_spot`, or `light_environment`.

**Comment by slambo311** [comment]
Just realized, the lightmap updating probably isn't the reason, since the flickering trigger works just fine in sp_a2_fizzler_intro.

**Comment by magcius** [comment]
Portal 2 uses dynamic lights (`env_projectedtexture`) instead of lightmaps for those lights. I believe the lightmaps are broken -- I'm using kind of an esoteric setup for them (NPOT, UN16, texture array) so I'm not surprised some drivers break.

Can you go to https://webglreport.com/?v=2 and tell me what the Renderer and Unmasked Renderer strings say, and whether you see EXT_texture_norm16 in the Supported Extensions list?

**Comment by slambo311** [comment]
Renderer: WebKit WebGL
Unmasked Renderer: Mesa DRI Intel(R) HD Graphics 400 (BSW)
And yeah, EXT_texture_norm16 is there.

**Comment by slambo311** [comment]
Just realized, you should probably reopen this.

**Comment by magcius** [comment]
The lighting issue is separate; the maps aren't loading as a white screen anymore.

**Comment by slambo311** [comment]
Fair point.
