### ISSUE TITLE
Mario Odyssey + Source Engine lighting issues on Chromebooks

### ISSUE THREAD

**Issue by slambo311** [magcius/noclip.website#517]
We've already established this back on #512, but here we go.

Dynamic lights work fine, but all other lights just don't work, likely due to lightmaps not compiling correctly.

CPU: Intel(R) Celeron(R) CPU N3060 @ 1.60GHz (2 threads, 2.48GHz).
Renderer: WebKit WebGL
Unmasked Renderer: Mesa DRI Intel(R) HD Graphics 400 (BSW)
EXT_texture_norm16 is a supported extension

I only recently found out about the Mario Odyssey lighting, while adding some more level names to my fork. For Source, models are Fullbright, while the terrain/brushes are pitch black. For Odyssey, certain parts are pitch black, some parts are Fullbright, and some parts are just colors (likely vertex colors). Here are two examples of Odyssey's strange lighting, both taken from Metro Kingdom's 1-1 Theater:
![image](https://user-images.githubusercontent.com/61334045/165186042-85b7cd15-e374-4def-812e-8c9ef9eca970.png)
![image](https://user-images.githubusercontent.com/61334045/165186191-fe6d9a5e-d72b-47b7-8709-e7086a644885.png)

**Comment by magcius** [comment]
Mario Odyssey is in the Experimental section, and no part of the game's lighting is implemented at all.

Please limit your bug reports to a single game / issue at a time.
