### ISSUE TITLE
Source Engine lighting bugs with old Intel graphics card

### ISSUE THREAD

**Issue by slambo311** [magcius/noclip.website#518]
We've already established this back on #512 and #517 (this being a copy-paste of #517 just with a couple of changes), but here:

Dynamic lights work fine, but all other lights just don't work, likely due to lightmaps not compiling correctly.

CPU: Intel(R) Celeron(R) CPU N3060 @ 1.60GHz (2 threads, 2.48GHz).
Renderer: WebKit WebGL
Unmasked Renderer: Mesa DRI Intel(R) HD Graphics 400 (BSW)
EXT_texture_norm16 is a supported extension
Chrome version (at the time I originally posted this): Version 92.0.4515.162 64-bit
Chrome version (currently): Version 97.0.4692.102 64-bit

Models are Fullbright, while the terrain/brushes are pitch black.

Screenshots:
![image](https://user-images.githubusercontent.com/61334045/165190302-a784d3e3-84ca-448f-803c-194924b836f1.png)
![image](https://user-images.githubusercontent.com/61334045/165190339-0616adc1-ef65-40e2-971d-a102b4ff4d37.png)

**Comment by slambo311** [comment]
Alright. But I have a feeling that these pieces of code in the main and materials files could affect it:
![Screenshot 2022-04-27 2 10 42 PM](https://user-images.githubusercontent.com/61334045/165593369-3502889a-c71d-495c-a4db-595d2b2308b4.png)
![Screenshot 2022-04-27 2 14 34 PM](https://user-images.githubusercontent.com/61334045/165593354-1f957d77-e9d4-4d55-a475-5f50abce6aa4.png)
![Screenshot 2022-04-27 2 08 58 PM](https://user-images.githubusercontent.com/61334045/165593403-5022166f-9db1-4f0a-abc3-e709f6be58a3.png)
For a workaround, making a render hack that toggles `DEBUG_DIFFUSEONLY` and/or `DEBUG_FULLBRIGHT` could help, along with a slider for `shadowMapSize`. Obviously, it's not exactly fixing shadows, but it's better than pure darkness.
The lightmap updater might've mistaken my Chromebook for a phone (like most websites), though. Also, the `wantsLightmap` being disabled is pretty likely to be part of the problem. `shadowMapSize` might affect the compiling.

**Comment by magcius** [comment]
wantsLightmap is set to true when the surface material is marked as having a lightmap.

https://github.com/magcius/noclip.website/blob/abdd1a14db3503c39c0b630187fe22c5a3e59901/src/SourceEngine/Materials.ts#L2266-L2269

The shadow map size is related to the dynamic shadows cast by env_projectedtexture, which appears to be working for you. The static baked lightmaps are unrelated to that.

**Comment by slambo311** [comment]
Oh, ok.

**Comment by slambo311** [comment]
Also, every couple of seconds the "Lightmaps built" counter in statistics goes up a bit, then goes straight back to 0 like 6 frames later. Usually happens when I'm moving the camera, but it happens while a map's loading too.
![image](https://user-images.githubusercontent.com/61334045/165625178-38f0098b-528d-4384-adc5-4916f38c250c.png)
Here's a screenshot of my statistics on HL2's background01, while the camera was in the default position, if this helps any.
![image](https://user-images.githubusercontent.com/61334045/165625302-115066ff-b2bd-4df4-a020-760fde860159.png)
And another, this time the screenshot was taken while the camera was looking at the "exterior" of the box where Breen normally is.

**Comment by slambo311** [comment]
Just thought of another workaround, having pre-compiled lightmaps in the files. Maybe make it so it only loads when some "Enable Pre-Compiled Lightmap" render hack's toggled, so it's optional.

**Comment by slambo311** [comment]
Alright, so my Chromebook finally decided to update from 92.0.4515.162 to 97.0.4692.102, still affects that version, too. I know flashlights are projected textures and aren't affected by lightmaps, but just saying, they work fine.

Here's some screenshots, if it helps.

Flashlight off:
![image](https://user-images.githubusercontent.com/61334045/169825625-4a6b5a36-e2a5-4f80-9a7c-9c6e6a2ec497.png)
Flashlight on:
![image](https://user-images.githubusercontent.com/61334045/169825567-a4802cce-3e01-4154-8080-362952f9c950.png)

Yeah, I doubt I'm helping at all.

**Comment by slambo311** [comment]
To help a little more, here's the stuff from the WebGL 2 report
![Screenshot 2022-05-24 9 31 21 AM](https://user-images.githubusercontent.com/61334045/170047537-ec365d6a-ce16-4271-a875-b77546745d44.png)
![Screenshot 2022-05-24 9 31 32 AM](https://user-images.githubusercontent.com/61334045/170047522-2625842f-9571-4393-84ec-bfce56c52694.png)
![Screenshot 2022-05-24 9 31 41 AM](https://user-images.githubusercontent.com/61334045/170047498-5a5e4236-f90a-4bac-af40-f8e0aceb2b8d.png)

**Comment by slambo311** [comment]
I finally updated to the latest update my Chromebook can support, 101.0.4951.72, and it still doesn't load lightmaps. Now that I think about it, I'm pretty sure my Chromebook used to have a little blue sticker that said "Intel" on it, so I think you're right about it being an old Intel graphics card bug.

**Comment by slambo311** [comment]
So recently I got another Chromebook (still have the old one), and it's a newer model, but the bug still happens, plus it has a sticker that says "intel inside", so I guess all Chromebooks from my school district use a crappy Intel graphics card. So hopefully you can add support for old Intel graphics cards.

**Comment by slambo311** [comment]
Alright, it seems to be fixed now
