### ISSUE TITLE
Dependencies should include yarn

### ISSUE THREAD

**Issue by omgitsraven** [magcius/noclip.website#53]
I'm trying to build the project locally, and one of the problems I ran into was that doing `npm run asbuild` would tell me `'yarn' is not recognized (etc)`. Doing `npm install yarn -g` fixed it.

(I'd add it to the package.json in a pull request myself, but I'm not sure what version is actually required, and I don't want to set it too high for nothing...)

**Comment by magcius** [comment]
yarn is a replacement for npm, so you really shouldn't be using npm in the first place. I'm not sure what the standards and best practices for that are though.

**Comment by omgitsraven** [comment]
OK, in that case, I guess my new thought is: there should be something in the way of build instructions :) I saw a package.json and assumed it was npm, that might explain why the end result was having errors…

**Comment by magcius** [comment]
There is a Getting Started guide accessible in the Discord server linked from the README -- you can also contact me directly or file GitHub Issues if you have questions. Maintaining multiple contributor guides is not something I want to do right now, so the Discord one will be the canonical one.

**Comment by omgitsraven** [comment]
That's fine! Maybe you could mention where to find it in the readme though, so people don't have to ask in an issue to find out :)

**Comment by magcius** [comment]
Ah, great point. I just cleaned up and updated the README.
