### ISSUE TITLE
Mario Kart 8 Deluxe: incorrect colours on Intel iGPU

### ISSUE THREAD

**Issue by Tatsh** [magcius/noclip.website#533]
This is with Intel UHD TGL GT1 on Linux. There's also a strange dot crawl type effect going on with most faces.

![20220828-0001](https://user-images.githubusercontent.com/724848/187077575-9b63189d-8981-463a-99fe-d9fe24b4bea7.png)

**Comment by magcius** [comment]
Please file a bug with Mesa. The issue is in your graphics driver.

**Comment by Tatsh** [comment]
Mesa bug: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7137

**Comment by magcius** [comment]
Should be improved by 2efb8e974bf3190537566c241cd07dc6c8d8cf77.
