### ISSUE TITLE
[Suggestion] Trigger Improvements

### ISSUE THREAD

**Issue by slambo311** [magcius/noclip.website#537]
Basically, something where when you press a certain key, it activates Source Engine triggers that are in the middle of the screen, similar to how the use button from the actual games works. Would be pretty useful.

**Comment by magcius** [comment]
likely not going to happen, it would require a lot of work to find the closest usable object (need to implement world collision, for instance), and the E key is already taken up for a different feature.

**Comment by slambo311** [comment]
I guess you could add a menu with a list of triggers instead, so when you click on one of triggers, it activates.

**Comment by slambo311** [comment]
Still though, if the use key idea is used, the large amount of work would likely be worth it. Besides, you don't really need the world collision part.

**Comment by slambo311** [comment]
Alright, I got another (slightly worse) idea. Have it so all entities/triggers that require something such as the use key to be activated (such as func_button and func_door) act like normal triggers, just activating when the camera is moved into them.
