### ISSUE TITLE
Where do data files go so that parcel will include them?

### ISSUE THREAD

**Issue by omgitsraven** [magcius/noclip.website#54]
I've switched over to yarn, and the project builds to the point of hosting a seemingly-functional version of the website when I run `yarn run start`. (And, I know that the github checkout doesn't include the data files.) I ran it with no data files, and tried loading the first map (Luigi Circuit), and then manually downloaded from the real site the path that the XHR request was made to (`data/mkwii/beginner_course.szs`), and added it to the local `data` directory, and re-ran `yarn run start`. But, the XHR acts exactly like before: it supposedly returns 200, but in practice it just redirects to the root, just like it does when the .szs file isn't there (I guess this is some default behaviour of parcel?)

What is the intended way to test the site locally with (some) data files? Have I just got the files in the wrong place, or am I supposed to be viewing the compiled version with something other than `yarn run start`?

**Comment by magcius** [comment]
There is a symlink from dist/data to data, but git on Windows does not create symlinks by default for some reason. You can delete the random file at dist/data and replace it with a data folder, and put your data files in there.

At some point there I had a better mechanism for Parcel with https://github.com/parcel-bundler/parcel/pull/2461 but they rejected my pull request. I'll make this work at some point.

**Comment by omgitsraven** [comment]
That worked, thanks!
