### ISSUE TITLE
[Suggestion] Wireframe Render Hack

### ISSUE THREAD

**Issue by Henry00IS** [magcius/noclip.website#545]
I was looking into how ZeldaMM uses vertex colors for lighting. I noticed that they have very precise parts of the world affected by them and wanted to have a look at the wireframe of the world. This would let me find out whether they cut up the walls just for precise vertex placements. Unfortunately toggling to a wireframe view doesn't appear to be a feature anywhere in this project.

Thank you for this website, it's amazing!

**Comment by magcius** [comment]
This is a very popular request. Unfortunately, due to WebGL limitations, wireframe mode is difficult to implement, so I am unlikely to implement this.
