### ISSUE TITLE
Issue with SMG2 worlds loading

### ISSUE THREAD

**Issue by rhit-vonbarke** [magcius/noclip.website#546]
The website seems to no longer be able to load any SMG2 worlds, at all. The page title updates, but the URL doesn't, and the view hangs on a black screen. I believe this is something that a very recent patch broke, as I didn't have this problem when viewing worlds two days ago (October 11th 2022)

Clearing cookies/cache and running in an incognito tab do not fix the issue

**Comment by magcius** [comment]
I believe this is fixed now.
