### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by billwurtz** [magcius/noclip.website#55]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

Windows 10 
Idk
The latest chrome version
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/44531381/55093561-5bad2800-5093-11e9-9440-29c7573d8bc0.png)

**Comment by magcius** [comment]
Hi! Can you make sure hardware acceleration is turned on? https://www.lifewire.com/hardware-acceleration-in-chrome-4125122
