### ISSUE TITLE
Firefox 103 error "Uncaught (in promise) DOMException: The operation is insecure."

### ISSUE THREAD

**Issue by amberdambey** [magcius/noclip.website#550]
Forgive me if I don't understand what causes this error; I'm fairly inexperienced with JavaScript and WebGL.
When viewing any page, instead of initializing the WebGL context, Firefox 103 throws this error:
![image](https://user-images.githubusercontent.com/99459304/204119928-ece131b7-4af2-4bb5-83c6-100ff61343ce.png)
I have tested this in both private and standard windows, as well as double-checking with Chromium-based browsers. It seems as if this only occurs when the security settings are set to Standard or Strict, but I can use the site normally when it is set to Custom with all options allowed:
![image](https://user-images.githubusercontent.com/99459304/204119987-e4583c39-2c76-45b3-90cd-10515601a9cd.png)
I assume this means that I need to somehow interact with the page (clicking or pressing any key) before any JavaScript code runs? I didn't have to do that with Firefox 102 or earlier.

**Comment by magcius** [comment]
Yeah, this is a known bug, I have to track down where it's coming from...
