### ISSUE TITLE
1

### ISSUE THREAD

**Issue by mhmdpse** [magcius/noclip.website#564]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:

**Comment by slambo311** [comment]
Damn, even I make better issues than these, and I've unintentionally annoyed the crap out of several developers

**Comment by magcius** [comment]
Please answer the questions in the template.
