### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by lordking5711** [magcius/noclip.website#566]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:

![browser](https://user-images.githubusercontent.com/57830944/213116720-241c2ddc-8560-4caf-b280-b031ef40e422.JPG)
![specs](https://user-images.githubusercontent.com/57830944/213116727-315151bd-a577-410b-b0a5-b16ec405e4cd.JPG)
![webgl2](https://user-images.githubusercontent.com/57830944/213116729-ef490bb0-27ac-4990-a01a-2ca490439c8c.JPG)

**Comment by magcius** [comment]
Make sure hardware acceleration is enabled.
