### ISSUE TITLE
[Goldsrc] Strange geometry

### ISSUE THREAD

**Issue by slambo311** [magcius/noclip.website#573]
![image](https://user-images.githubusercontent.com/61334045/216979079-f7a8ec14-4300-4351-bb1b-13b951a5dcd4.png)

Several pieces of geometry are all in one spot here, such as the chair Barney spins on, parts of the door, and some lights. The triggers are visible, too.

**Comment by slambo311** [comment]
![image](https://user-images.githubusercontent.com/61334045/220421787-19781079-e6be-4fd3-940c-40b20f16634d.png)
Alright, that fixed the triggers being visible, but now the geometry is just gone, including (as far as I can tell) pretty much everything that isn't part of the main world mesh (doors, elevators, glass, microwave casseroles, etc.)

**Comment by magcius** [comment]
Yep, that's what happens right now.
