### ISSUE TITLE
Portal 2 Workshop breaks the mouse somehow

### ISSUE THREAD

**Issue by slambo311** [magcius/noclip.website#575]
So after opening the workshop, just moving my mouse onto anything on the selection menu makes it load, despite me not clicking. Here's a poorly-made video:
[Screen recording 2023-02-24 10.56.44 AM.webm](https://user-images.githubusercontent.com/61334045/221225623-f7f669ac-8c9c-4233-9885-9a471d3d00e6.webm)

Only clicking I did here was selecting Portal 2, the workshop, and minimizing the workshop.

**Comment by notfrying1pans** [comment]
I think it's an issue with how the ui shows up

**Comment by slambo311** [comment]
> I think it's an issue with how the ui shows up

Yeah, that's pretty obvious.

Anyway, despite my lack of coding knowledge, I looked in the code myself (seeing as Jasper likely is sick of my crap), and yeah, couldn't find a thing.

**Comment by PFedak** [comment]
Should be fixed now
