### ISSUE TITLE
noclip.website

### ISSUE THREAD

**Issue by ItzHype** [magcius/noclip.website#577]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Windows 10 x64
What NVIDIA 9800GT are you using?
What Mozilla Firefox 110.0 are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/111016408/221358417-62dc6542-715a-4249-b876-314f3446a8ee.png)

**Comment by magcius** [comment]
Make sure hardware acceleration is enabled in your browser settings.
