### ISSUE TITLE
webgl2 problem

### ISSUE THREAD

**Issue by IconicAlex** [magcius/noclip.website#584]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![Screenshot 2023-04-21 022618](https://user-images.githubusercontent.com/131408146/233491661-6f2af0bb-aae9-4a3b-bfe9-0df88ca9e823.png)

**Comment by magcius** [comment]
Please answer the questions
