### ISSUE TITLE
Toshiba windows 10

### ISSUE THREAD

**Issue by rsvent** [magcius/noclip.website#590]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **toshiba windows 10** are you using?
What **GPU and Driver Version** are you using?
What **microsoft edge** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![Screenshot 2023-05-21 175644](https://github.com/magcius/noclip.website/assets/134208118/b946d042-9353-477f-aed2-74d17cb19b88)

**Comment by magcius** [comment]
Please make sure hardware acceleration is enabled in Edge's settings.
