### ISSUE TITLE
browser supports WebGL 2, but it is disabled or unavailable.

### ISSUE THREAD

**Issue by lordking5711** [magcius/noclip.website#591]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **Windows 10 Home and 2H22 ** are you using?
What **NVidia GeForce 9500 GT and GeForce 342.01 Driver** are you using?
What **Google Chrome Version 113.0.5672.127** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://github.com/magcius/noclip.website/assets/57830944/9b2c0041-bb1c-4a51-a674-9d652200a743)

**Comment by magcius** [comment]
Please make sure hardware acceleration is enabled in Chrome's settings.

**Comment by lordking5711** [comment]
![image](https://github.com/magcius/noclip.website/assets/57830944/1496d6e9-1bb8-43af-bdbd-1659833ed05b)
still doesn't work

**Comment by magcius** [comment]
That's strange. You might find some helpful information in chrome://gpu, it's possible your device is blocklisted, I'm not sure.
