### ISSUE TITLE
my pc is supported for webgl2 but error occring

### ISSUE THREAD

**Issue by itsnaruto30** [magcius/noclip.website#593]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://github.com/magcius/noclip.website/assets/130277666/6187c945-aa56-40d8-8073-7694c4491282)

**Comment by magcius** [comment]
Please answer the questions. Can you also make sure to tell me the error message you see on noclip.website?
