### ISSUE TITLE
Google Pixel Rendering Issues

### ISSUE THREAD

**Issue by nico-apps** [magcius/noclip.website#594]
I'm having issues running noclip.website on my Google Pixel 7. Whenever I open up the website, it looks like this:
![Screenshot_20230623-191112](https://github.com/magcius/noclip.website/assets/35093969/5db5ac15-b5da-47cb-8522-438e895c4972)
![Screenshot_20230522-062656](https://github.com/magcius/noclip.website/assets/35093969/30b8cee7-4529-429a-b037-e7ab0a66d05e)
I'm using `Chrome 114.0.5735.130`. How can I fix this issue?

**Comment by magcius** [comment]
Please file a bug with your hardware manufacturer and OS vendor.
