### ISSUE TITLE
Camera Speed Broken

### ISSUE THREAD

**Issue by ShanuJackal** [magcius/noclip.website#598]
Camera speed is completely broken, showing NaN as its value when you try to use the scroll wheel. It is unable to be changed. It also breaks other camera controls unable to be used as a result. Reloading does not work, You must close the tab and open a new one to be able to control the camera again. I tried using the backslash and shift keys to change camera speed, but nothing happened.

**Comment by PFedak** [comment]
What OS/browser are you using? Can you get this to happen consistently on any game map or just specific ones? We can add some defensive logic around the camera speed but I haven't seen this before.

**Comment by ShanuJackal** [comment]
Windows 11 Pro 22H2, Mozilla Firefox

Tested on Chrome, works there

**Comment by Miepee** [comment]
On Arch Linux + Firefox there's a similar issue, where the camera speed is *very* slow. I can change the slider for it, but it does nothing. Chromium again does not inhibit any of these issues.

**Comment by magcius** [comment]
Bizarre. I do try to normalize the deltaY parameter that comes out of the mouse wheel event, so I wonder why Firefox is so much slower for it <https://github.com/magcius/noclip.website/blob/master/src/InputManager.ts#L199-L203>

**Comment by magcius** [comment]
So far, I've been unable to reproduce this with Firefox on Windows. I'd be curious if anyone can help me debug it. My best guess is that an invalid wheel event is making it in without a deltaY property and screwing things up. If you disable all extensions, does that fix the issue?

**Comment by Miepee** [comment]
No, even with all extensions disabled the camera speed is still messed up.
How would I be able to help with debugging, without needing to compile from source? is there a way to see mouse variables in the statistic tabs?

**Comment by magcius** [comment]
I was mostly interested in the bug where the camera speed becomes NaN. If the camera speed slider is doing nothing, that seems like it could be a different bug. One thing to check is to make sure that the camera speed is making it all the way to the camera controller. Check `main.viewer.cameraController.keyMoveSpeed` in the F12 Console. When the slider is at the low end, it should be 8, and when it's at the high end, it should be 200.

**Comment by magcius** [comment]
Yeah, that's working correctly. The bizarre thing is that from there, all the code using the camera speed is our own math, and I can't imagine any way Firefox could be messing this up.

**Comment by Miepee** [comment]
Just noticed: this could potentially be size or multi monitor related.
Firefox maximized on one monitors -> slow
Firefox stretched to cover both monitors -> less slow
Firefox stretched to be longer than both my monitors -> even less slow.

At least it feels like it. Still wouldn't explain why the camera speed doesn't have any effect tho.

**Comment by magcius** [comment]
@Miepee is this about the camera speed when traveling using WASD, or about the speed of rotation when clicking and dragging with the mouse?

**Comment by Miepee** [comment]
The latter.

**Comment by magcius** [comment]
OK, then I believe you're seeing the same issue as #624, unrelated to the original reporter's issue. It appears to be an issue with Firefox's pointer lock implementation on Linux.
