### ISSUE TITLE
Gamecube games do not render properly in Firefox 63

### ISSUE THREAD

**Issue by Ivoah** [magcius/noclip.website#6]
![image](https://user-images.githubusercontent.com/2159017/47619418-d3f7c900-dab4-11e8-86e6-e75e322abe7d.png)
![image](https://user-images.githubusercontent.com/2159017/47619444-00abe080-dab5-11e8-861c-9dac14f722c4.png)

**Comment by magcius** [comment]
I've identified the issue and will be fixing this soon.

**Comment by magcius** [comment]
I've found and identified the issue with Macs. Due to the nature of the bug, each game will have to be fixed independently, but so far I've fixed the GameCube / Wii games. Could you verify that the bug is fixed in this link? https://noclip.website/#mkwii/beginner_course

**Comment by Ivoah** [comment]
That map looks fine on FF 65.0.1 on macOS 10.14.3

**Comment by magcius** [comment]
Thank you for confirmation, and sorry for the wait! It'll take me some time to fix the rest of the maps. I'll close this ticket when the task is done.

**Comment by Ivoah** [comment]
I just checked all the other gamecube maps and they seemed to work just fine as well

**Comment by magcius** [comment]
Everything (except Splatoon) should be working at this point. If something is not working, please reopen the bug.
