### ISSUE TITLE
Add feature to disable sprites/enemies

### ISSUE THREAD

**Issue by citrusui** [magcius/noclip.website#60]
It would be a nice addition if there were a way to hide sprites or enemies from showing up when browsing in-game maps.

For example, I recently noticed the map "Zora's River" from Ocarina of Time 3D had been updated to include two sprites: a chicken and an octarock.

[(Link to the map)](https://noclip.website/#oot3d/spot03;ZNCA8r==k-y8ySEh@4ur&%7d%7d9V$Xtg[$,q7Z~8:!s+4avhn:orW7e9DaObr66DK:nL7[sbN=)

![Screenshot from 2019-04-04 18 02 49](https://user-images.githubusercontent.com/9056756/55591701-3e680180-5704-11e9-8f8a-ce3291c79ae0.png)

I took a picture of the same map a few weeks ago and they weren't there.

![20190224_024408794_iOS](https://user-images.githubusercontent.com/9056756/55591929-ea115180-5704-11e9-8c5d-868fc1761855.png)

Thanks for all the work you've done on the website. It's an insanely useful tool.

**Comment by magcius** [comment]
Out of curiosity, why do you want to disable actors?

**Comment by citrusui** [comment]
No major reason. I'm working on a multimedia art/design project that involves taking screenshots of maps in-game though. The screenshots also make good wallpapers, now that I think about it...

**Comment by magcius** [comment]
You can show/hide individual objects with the developer tools console. Press F12 and then type `main.viewer.scene.roomRenderers[0].objectRenderers[0].visible = false;`. You might need to adjust both the room number and the object number. Set things to `true` to make things visible again.

For now, I'm not planning on making any UI for showing/hiding individual actors.

**Comment by citrusui** [comment]
just for future reference, here's what i did to make it look somewhat more deserted:

```
main.viewer.scene.roomRenderers[0].objectRenderers[0].visible = false; // removes color from skybox
main.viewer.scene.roomRenderers[0].objectRenderers[1].visible = false; // removes animated clouds
main.viewer.scene.roomRenderers[0].objectRenderers[3].visible = false; // removes octarock
main.viewer.scene.roomRenderers[0].objectRenderers[6].visible = false; // removes chicken
main.viewer.scene.roomRenderers[0].objectRenderers[16].visible = false; // removes the resting spot of the chicken
```
