### ISSUE TITLE
[GTA] Textures not loading

### ISSUE THREAD

**Issue by TylersHuman** [magcius/noclip.website#600]
I am having trouble loading textures for both GTA San Andreas and GTA Vice City. 

Every other game loads perfectly but for these 2 games every texture is solid black, for full map and all interiors.

These worked fine yesterday (7/27/2023) so this seems to have happened recently.

This issue is present on multiple PCs and multiple browsers (Chrome, Firefox and Edge)

![GTA San Andreas Textures](https://github.com/magcius/noclip.website/assets/18449258/544ba668-7354-47d8-afdd-a34c39fa4595)
![GTA Vice City Textures](https://github.com/magcius/noclip.website/assets/18449258/cfb55c52-b8aa-46cd-97ca-b5b9fe53c628)

**Comment by magcius** [comment]
Likely due to https://github.com/magcius/noclip.website/commit/3ad0ffccbb392f824a924be67883d900b6ba1b1d

I thought the Chrome bugs being fixed would solve it, possible we're still doing something wrong there. Thanks for the report, I'll investigate.
