### ISSUE TITLE
WebGL error but my browser supports WebGL2

### ISSUE THREAD

**Issue by Copen-08** [magcius/noclip.website#61]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:

Windows 10
Onboard GPU (no graphics card)
Firefox
![big-err](https://user-images.githubusercontent.com/35631331/55691703-c5f87f00-5955-11e9-89e6-0f4d83821105.PNG)

**Comment by magcius** [comment]
Can you take a screenshot of WebGL Report with more of the system included in the screenshot? Thank you.
