### ISSUE TITLE
[GAME MAP REQUEST] Mafia : the city of Lost Heaven

### ISSUE THREAD

**Issue by rahulroy9202** [magcius/noclip.website#611]
Steam : https://store.steampowered.com/app/40990/Mafia/
Wikipedia : https://en.wikipedia.org/wiki/Mafia_(video_game)

I could not find a alternative way to raise this request. So adding here. 

Thank You

**Comment by magcius** [comment]
I do not accept new requests, unless someone is willing to contribute a renderer for it.
