### ISSUE TITLE
Noclip don't work :(

### ISSUE THREAD

**Issue by aestheticallyUnpleasing** [magcius/noclip.website#62]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
Windows 7 64-bit

What **GPU and Driver Version** are you using?
Tbh Idk, but the driver version is 6.1.7600.16385.

What **Browser and Version** are you using?
Google Chrome, Version 73.0.3683.103 (aka latest version)

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/49382766/55696522-b2eeb900-5a00-11e9-8aaa-cc6df93b10ea.png)

**Comment by magcius** [comment]
As the screenshot suggests, WebGL 2 is disabled. Please try to find which GPU you have installed. You can find your current GPU under the "Display adapters" section of Device Manager.

**Comment by magcius** [comment]
@aestheticallyUnpleasing As the screenshot suggests, WebGL 2 is disabled. Please try to find which GPU you have installed. You can find your current GPU under the "Display adapters" section of Device Manager.
