### ISSUE TITLE
P2 Workshop

### ISSUE THREAD

**Issue by ertup0** [magcius/noclip.website#622]
Workshop maps no longer load. The search still works but nothing happens after selecting the map

**Comment by magcius** [comment]
It seems like the CORS proxy I'm using for it is running rather slow for large file downloads, and also stopped reporting progress at some point. It will complete eventually, but will take a *very* long time.

**Comment by ertup0** [comment]
So instead of fixing it,  you just fully removed it. wow

**Comment by magcius** [comment]
Yes. I tried a few different things to fix it, but there's no easy option -- Steam's servers aren't really designed for me to be downloading files from them like this. Since then, I got another request about it, and decided to remove it since I couldn't support it.
