### ISSUE TITLE
noclip.website isn't working

### ISSUE THREAD

**Issue by DarkJohn117** [magcius/noclip.website#63]
Hi! noclip.website isn't working for me!  
Nothing urgent for me, but maybe that stuff helps you ;)
Here are the answers to the asked questions:

What **OS and Version** are you using?
**macOS Mojave Version 10.14.4 (18E226)**

What **GPU and Driver Version** are you using?
**NVIDIA GeForce GT 755M 1GB**, probably the latest macOS Driver.

What **Browser and Version** are you using?
**Firefox Quantum 66.0.2 (64-bit)**

Screenshot of webGL Config:
![webGlcapture](https://user-images.githubusercontent.com/43026173/55934875-625ea200-5c32-11e9-8fde-224ca02d5c0d.png)

**Comment by magcius** [comment]
Can you tell me what error message you are getting?

**Comment by magcius** [comment]
@DarkJohn117 Could you please tell me what error message you are getting?
