### ISSUE TITLE
Your browser does not appear to have WebGL 2 support.

### ISSUE THREAD

**Issue by mica95zoud** [magcius/noclip.website#633]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![Sans titre](https://github.com/magcius/noclip.website/assets/88750039/6816cd45-fb95-46b4-8bb7-314030ffabdf)

**Comment by magcius** [comment]
Please answer the questions; note that noclip requires Hardware Acceleration to be enabled.
