### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by niki200515** [magcius/noclip.website#670]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here: 
![Screenshot_2](https://github.com/magcius/noclip.website/assets/168952338/d87968f3-ac65-4ec1-822d-2e56c4467049)

**Comment by magcius** [comment]
Either your GPU drivers or your browser is too old. noclip.website requires WebGL 2.0 support.
