### ISSUE TITLE
Wind Waker distance fog appears to be broken

### ISSUE THREAD

**Issue by christian-macneill** [magcius/noclip.website#683]
Example image from the forbidden woods, but this seems to be the case for every level.
![image](https://github.com/magcius/noclip.website/assets/54046010/fb24e473-5222-41d8-8c92-92bd516ad895)

**Comment by magcius** [comment]
Ugh; nice catch. I believe this is a Chrome bug in the implementation of EXT_clip_control. I've [filed a bug](https://issues.chromium.org/issues/347197920) with Chromium; for now I'll disable EXT_clip_control usage in noclip.
