### ISSUE TITLE
WebGL2 Support - Firefox

### ISSUE THREAD

**Issue by Shahelion** [magcius/noclip.website#691]
What **OS and Version** are you using? _**Windows 10**_
What **GPU and Driver Version** are you using? _**AMD Radeon R7 200 Series**_
What **Browser and Version** are you using? _**Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0**_

_**Also, in Firefox's preferences, it says that WebGL2 is enabled, and get.webgl.org says my browser supports it.**_

Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![image](https://github.com/user-attachments/assets/0e8e9cfb-2a74-4f01-8a67-29b93642dd76)

**Comment by magcius** [comment]
Sorry for the delay here. It seems that Firefox does not think your GPU supports WebGL 2. There might be more information in `about:support`, or you can try using a different browser. There is also experimental WebGPU support at https://noclip.website/?webgpu , but it might not work with all games yet.

**Comment by Shahelion** [comment]
The experimental site says my browser is too old, which is strange because it's up to date Firefox.

**Comment by magcius** [comment]
Ah, right, I forgot Firefox hasn't yet rolled out WebGPU yet.
