### ISSUE TITLE
I WANT TO GET IN THE NOTECLIP.WEBSITE PLEASE!!!!

### ISSUE THREAD

**Issue by mateo246** [magcius/noclip.website#701]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **Version** are you using?
What **GPU** are you using?
What **Browser** are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
https://x.com/MateoburgosCcca/status/1830707004685385825

**Comment by magcius** [comment]
Please answer the questions provided in the form. The Twitter link you provided is inaccessible for me.
