### ISSUE TITLE
fix noteclip.website please fix it!

### ISSUE THREAD

**Issue by mateo246** [magcius/noclip.website#703]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What OS are you using?
What GPU are you using?
What Browser are you using?
Please take a screenshot of https://webglreport.com/?v=2 and paste it here:
![LOOK!!](https://github.com/user-attachments/assets/281002f3-4a71-4a16-8573-3d1036eddfd4)

**Comment by MesaBlack** [comment]
[erm
](https://github.com/magcius/noclip.website/issues/701)

**Comment by magcius** [comment]
Please make sure that hardware acceleration is turned on in Chrome's settings. Also, please tell me what OS, browser, and GPU you are using.

**Comment by mateo246** [comment]
Browser
