### ISSUE TITLE
Fix it Jasper Fix it!

### ISSUE THREAD

**Issue by mateo246** [magcius/noclip.website#705]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Version
What **GPU and Driver Version** are you using? GPU
What **Browser and Version** are you using? Browser
![LOOK!!](https://github.com/user-attachments/assets/81c93754-58ea-4337-9ae9-054b126ed433)

Please take a screenshot of https://webglreport.com/?v=2 and paste it here:

**Comment by magcius** [comment]
This is the third bug report you've opened. Have you tried [the suggestions I made last time](https://github.com/magcius/noclip.website/issues/703#issuecomment-2351118520)? If so, what happened?

**Comment by MesaBlack** [comment]
@magcius I think this guy is tired

**Comment by magcius** [comment]
@MesaBlack please do not comment in unrelated issues on behalf of the project.

**Comment by MesaBlack** [comment]
ok

**Comment by mateo246** [comment]
please fix it!!!
