### ISSUE TITLE
WebGL Not Working

### ISSUE THREAD

**Issue by Skipper93653** [magcius/noclip.website#71]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10 v1803
What **GPU and Driver Version** are you using? ATI Radeon HD 2600 Pro v8.970.100.9001
What **Browser and Version** are you using? Google Chrome v73.0.3683.103
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/40239000/56456900-b8d28b80-636a-11e9-8142-bc69066a4bfc.png)

**Comment by magcius** [comment]
@Skipper93653 did you try upgrading your graphics drivers and updating Chrome itself? Also try enabling Hardware Acceleration in Chrome.
