### ISSUE TITLE
webgpu error message not specific enough to be helpful (on Firefox Linux RX7600)

### ISSUE THREAD

**Issue by thingsiplay** [magcius/noclip.website#724]
* Firefox: `132.0.2 (64-bit)`
* OS: `EndeavourOS x86_64 Linux 6.11.9-arch1-1`
* GPU 1: `AMD Radeon RX 7600 (RADV NAVI33) [Discrete] Mesa 24.2.7-arch1.1`
* GPU 2: `AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO) [Integrated] Mesa 24.2.7-arch1.1`

The website loads and clicking on a scenery will seemingly download something, but the screen stays black without showing anything. Firefox is the newest one. It would be nice if the message would tell me the actual feature that is needed here. So I can investigate what the problem is. For the record, the hardware acceleration is on in the settings

The Browser Console gives me this error:

> NotFoundError: No such JSProcessActor 'BrowserToolboxDevToolsProcess' 3

The error message on https://noclip.website/?webgpu just says: 

> Your browser is too old and is missing support for web APIs that I rely on.
> 
> Please try to update your browser to a more recent version. 

![Screenshot 2024-11-20 at 07-51-12 noclip](https://github.com/user-attachments/assets/d392a4b3-d59b-427a-bec1-bf5c3f04b40f)

The report from https://webglreport.com/?v=2 get me following:

![Screenshot 2024-11-20 at 12-46-53 WebGL Report](https://github.com/user-attachments/assets/fe70eef7-2aea-4e39-80e7-488fc52e0ec2)

**Comment by magcius** [comment]
Firefox doesn't support WebGPU yet (outside of enabling it through about:config in Nightly), and WebGPU is still in beta in noclip, I haven't invested any time into better error messages.

If you're looking to use the website, use WebGL 2 for now.

**Comment by thingsiplay** [comment]
This information should be part of the error message. I'm not sure why this issue is closed as completed.

**Comment by magcius** [comment]
Because, as I said, WebGPU support is not yet complete.

You are also trying to use WebGPU on a browser that does not currently support it, so the error message is not wrong. Your browser is missing support for web APIs that I rely on.
