### ISSUE TITLE
Model Viewer Acting Up

### ISSUE THREAD

**Issue by PooperDeDooper** [magcius/noclip.website#82]
As of this month, whenever I try to pan the camera around in an environment, the models will rapidly load and unload, objects will begin to spin around and fly out, and various messed up graphics will appear on screen. I have been using the website for months and this did not occur before June of 2019 for me. Nothing in my setup has changed, although I noticed the "Scenario Viewer" is now in English, which appears to have happened at the same time as the graphical glitches for me. I can provide a video if necessary, and this has so far occurred on every game I've tried.

**Comment by magcius** [comment]
Can you please list what games you're having these issues with? What operating system, browser, and GPU?

**Comment by PooperDeDooper** [comment]
My OS is Windows 7, browser is FireFox, and my GPU is an Nvidia GT 1030. I've tested this on Mario Galaxy's 1 and 2, Luigi's Mansion, Wind Waker, and Mario Sunshine, all to the same results in every level I've tried.

**Comment by magcius** [comment]
Thank you; I've reproduced the issue on Firefox Developer Edition and am currently looking into it.

**Comment by PooperDeDooper** [comment]
If it helps at all, I only began to experience this a few days ago. I don't know if something changed in the most recent FireFox or if something changed behind the scenes at NoClip, but either way best of luck!

**Comment by magcius** [comment]
Fixed by c67fa910842631e0fb332e92416d64f8dcf66c48.
