### ISSUE TITLE
i did what you said and everything else but it still isnt work.

### ISSUE THREAD

**Issue by jjfjjfjfkdjfkffjghhhg** [magcius/noclip.website#84]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using?
What **GPU and Driver Version** are you using?
What **Browser and Version** are you using?
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![Capture](https://user-images.githubusercontent.com/51523886/59172493-9f400a00-8b8b-11e9-87d7-524e95d19305.PNG)
![a](https://user-images.githubusercontent.com/51523886/59172497-a5ce8180-8b8b-11e9-8677-231b1401802d.PNG)

**Comment by jjfjjfjfkdjfkffjghhhg** [comment]
*working

**Comment by jjfjjfjfkdjfkffjghhhg** [comment]
and my browser is chrome and idk any more

**Comment by jjfjjfjfkdjfkffjghhhg** [comment]
*working

**Comment by magcius** [comment]
"Google SwiftShader" means you're running on software acceleration. Please make sure that hardware acceleration is enabled.
