### ISSUE TITLE
noclip website not working even though hardware acceleration is enabled and https://get.webgl.org/ shows a spinning cube

### ISSUE THREAD

**Issue by PkmnTrainerRed42** [magcius/noclip.website#85]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 7 Enterprise Service Pack 1 32-bit
What **GPU and Driver Version** are you using? Intel(R) HD Graphics(Core i5)
What **Browser and Version** are you using? Google Chrome 75.0.3770.100
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![webgl](https://user-images.githubusercontent.com/51059123/59721868-4a863a00-91f0-11e9-830c-30ce091a190f.PNG)

when i try to go to noclip.website it says "Your browser does not appear to have WebGL 2 support."
but when i go to https://get.webgl.org/ it shows a spinning cube and says my browser supports it
can you help? i have been looking forward to going on this website

**Comment by magcius** [comment]
`get.webgl.org` tests WebGL 1, not WebGL 2. I'm going to guess this is an issue with your GPU. Can you take a screenshot of the WebGL 1 tab of http://webglreport.com/ ?

**Comment by PkmnTrainerRed42** [comment]
![webgl 1](https://user-images.githubusercontent.com/51059123/59729961-8defa100-920e-11e9-8dd5-981ebe428b44.PNG)

**Comment by magcius** [comment]
Yeah, that looks like an unsupported device to me. `chrome://gpu` might have more information.

**Comment by mateo246** [comment]
I WANT NOCLIP.WEBSITE PLEASE I NEED IT!!!!!11
