### ISSUE TITLE
Metroid Prime 1 Broken

### ISSUE THREAD

**Issue by WhispersfromIO** [magcius/noclip.website#86]
Metroid Prime 1 for GameCube seems broken. The model assets seem to load but almost none of the surfaces do, and the few surfaces that do load seem really stretched. Used the latest versions of Chrome and Firefox with Win10 and got the same issue for both. The other GameCube games  all loaded fine from what I tested.

Screenshot of Impact Crater with all layers loaded. Showing the layers one by one doesn't fix anything.

![Screenshot_2019-06-19 Impact Crater - Metroid Prime 1 - noclip](https://user-images.githubusercontent.com/18041409/59816906-acb76b80-92d2-11e9-8039-9a2bb3404b9a.png)

P.S. This is a amazing website aside from not loading my favorite game!

**Comment by magcius** [comment]
Oof, apologies. I've recently been making large changes to the GameCube
core for performance reasons and I guess I forgot to test them with Metroid
Prime. Unfortunately I am heading out on a plane today. I'll fix as soon as
I can.

**Comment by magcius** [comment]
Fixed in 606de479a2a4da3b094110782153786dd3fba647.
