### ISSUE TITLE
my problem

### ISSUE THREAD

**Issue by LitKitten** [magcius/noclip.website#87]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10.
What **GPU and Driver Version** are you using? GPU: no info. Driver: WDDM 1.2.
What **Browser and Version** are you using? Google, latest update.
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/52213279/60116542-3ab5ab00-9746-11e9-8eab-0923ff87f086.png)

**Comment by magcius** [comment]
Did you try to enable hardware acceleration in chrome://flags ?
