### ISSUE TITLE
Super Mario Sunshine not displaying anything

### ISSUE THREAD

**Issue by TheCBarpsh** [magcius/noclip.website#89]
When I try to load any area from Super Mario Sunshine, it appears as a dark blue void. This occurs whether textures or vertex colors are enabled or not.
![Image of the void](https://i.ibb.co/3hMBjmM/Screen-Shot-2019-07-05-at-4-08-19-AM.png)

**Comment by magcius** [comment]
Fixed in d4688f716c5b3d211940577661f0e0a4f9a24192. Sorry for the breakage, and thanks for the report.
