### ISSUE TITLE
Linux Chrome browser incorrectly identified as lacking WebGL2 (No MSAA under Linux Chrome)

### ISSUE THREAD

**Issue by shypiguy** [magcius/noclip.website#9]
webglreport indicates webgl 2 is supported:

![screenshot from 2019-02-23 08-31-04](https://user-images.githubusercontent.com/16522715/53287684-68152c80-3745-11e9-9f01-83be06479ee7.png)

noclip says it isn't.

**Comment by magcius** [comment]
Can you tell me the exact error message that you got on noclip?

**Comment by magcius** [comment]
I believe the issue is the "Antialiasing: unavailable" and the "Samples: 0" under Framebuffer. The way that noclip.website is written relies on antialiasing. I'm curious why Ivybridge does not expose AA. I will separately investigate allowing support for bizarre non-AA hardware.

**Comment by aaaaaa123456789** [comment]
Here's my machine's webgl2 report:

![image](https://user-images.githubusercontent.com/6129020/55689864-7e2b2500-5960-11e9-90ba-55e08af7d9f3.png)
![image](https://user-images.githubusercontent.com/6129020/55689876-956a1280-5960-11e9-928b-47769c4a637f.png)
![image](https://user-images.githubusercontent.com/6129020/55689881-a87ce280-5960-11e9-96ad-646edb93dd51.png)

Antialising is supported, yet the website doesn't load:

![image](https://user-images.githubusercontent.com/6129020/55689890-bf233980-5960-11e9-9fb1-38d2e57597a0.png)

Needless to say, hardware acceleration is enabled.

**Comment by magcius** [comment]
Hardware acceleration is not supported -- you are using SwiftShader, a software implementation. The specific check that's used is for the number of samples in a GL_DEPTH_COMPONENT24 texture. Your browser is reporting no samples, which looks very wrong to me. Perhaps it only supports D32 textures? I'll try in a bit.

https://github.com/magcius/noclip.website/blob/master/src/viewer.ts#L241

**Comment by magcius** [comment]
https://github.com/magcius/noclip.website/commit/a292567626f38c7be57f9cfed5767d14653925fe
