### ISSUE TITLE
noclip.website isn't working

### ISSUE THREAD

**Issue by DoomesPro93** [magcius/noclip.website#90]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Mac OS 10.14.3
What **GPU and Driver Version** are you using? Intel UHD Graphics 617 1536 MB
What **Browser and Version** are you using? Chrome 76.0.3809.46

Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
<img width="701" alt="Screen Shot 2019-07-07 at 6 39 46 AM" src="https://user-images.githubusercontent.com/52625487/60767826-d4eceb80-a082-11e9-8151-248370e562de.png">

**Comment by magcius** [comment]
What error are you seeing?

**Comment by DoomesPro93** [comment]
This application requires hardware acceleration to be enabled.

Please enable hardware acceleration in your's browser settings.

If you have enabled hardware acceleration and are still getting this error message, please open a GitHub issue with as much as information as possible.

**Comment by magcius** [comment]
Did you make sure that hardware acceleration was enabled here? chrome://settings/?search=hardware+acceleration

**Comment by DoomesPro93** [comment]
It is enabled.

**Comment by magcius** [comment]
The bottom of chrome://gpu might have additional details. Do you see anything in the logs about "blacklisted"?

**Comment by DoomesPro93** [comment]
No I do not.

**Comment by magcius** [comment]
Somehow Chrome is deciding not to use the GPU -- and the answer for why will be somewhere on that chrome://gpu page. Sorry that I cannot provide more detailed help.
