### ISSUE TITLE
Oh no i wont work

### ISSUE THREAD

**Issue by PikachuAndLittenPlays** [magcius/noclip.website#92]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

What **OS and Version** are you using? Windows 10 I dunno what the version is.
What **GPU and Driver Version** are you using? I dunno
What **Browser and Version** are you using? Im using Microsoft edge I dunno the version
Please take a screenshot of http://webglreport.com/?v=2 and paste it here:
![image](https://user-images.githubusercontent.com/53200424/61674510-067fcc80-aca9-11e9-8b30-f8a900a201d9.png)

**Comment by PikachuAndLittenPlays** [comment]
![image](https://user-images.githubusercontent.com/53200424/61674555-27e0b880-aca9-11e9-891b-9e0b192a0feb.png)
I don't know why its doing this.

**Comment by PikachuAndLittenPlays** [comment]
![image](https://user-images.githubusercontent.com/53200424/61674588-5199df80-aca9-11e9-9283-31ed22f960b3.png)
I dunno

**Comment by magcius** [comment]
Your browser doesn't support WebGL 2. Try to enable hardware acceleration.
