### ISSUE TITLE
noclip.website is not working anymore

### ISSUE THREAD

**Issue by de-illest** [magcius/noclip.website#96]
Hi! Sorry to hear that noclip.website isn't working for you! Please answer the following questions:

windows 10 version 1903
GeForce GTX 1060 driver 431.60
Chrome 76.0.3809.87 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/31111823/62365608-cfb97a00-b524-11e9-8d93-cfe444f0c7d8.png)

**Comment by magcius** [comment]
You don't appear to have hardware acceleration enabled. Could you try enabling that and let me know if it solves your issue?

**Comment by de-illest** [comment]
strangely enough chrome said it was enabled when i looked at it in settings. After a reboot it's working now. thanks! :-)
